import fs from 'node:fs/promises';
import {build} from 'esbuild';
const cfg=JSON.parse(await fs.readFile('config.json','utf8'));
const production=process.argv.includes('--production');
if(production)cfg.allowDeveloperMode=false;
const folder=production?'build/production':'build/development';
const audio={}; // Only playable city and rest-class tracks are embedded.
for(const score of JSON.parse(await fs.readFile('assets/music/CITY-CREDITS.json','utf8')))audio[score.id]='data:audio/mpeg;base64,'+(await fs.readFile('assets/music/'+score.id+'.mp3')).toString('base64');
const art={};for(const city of ['taipei','tokyo','vegas','singapore','newyork','monaco','luxury-texture','ivory-texture','ui-taipei','ui-tokyo','ui-vegas','ui-singapore','ui-newyork','ui-monaco','logo','cg-poor','cg-rich'])art[city]='data:image/webp;base64,'+(await fs.readFile('assets/art/'+city+'.webp')).toString('base64');
for(const f of await fs.readdir('assets/art/ic'))if(f.endsWith('.webp'))art['ic-'+f.replace('.webp','')]='data:image/webp;base64,'+(await fs.readFile('assets/art/ic/'+f)).toString('base64');
for(const f of await fs.readdir('assets/art/mg'))if(f.endsWith('.webp'))art['mg-'+f.replace('.webp','')]='data:image/webp;base64,'+(await fs.readFile('assets/art/mg/'+f)).toString('base64');
const scores=JSON.parse(await fs.readFile('assets/music/ORIGINAL-SCORES.json','utf8'));for(const score of scores)audio[score.id]='data:audio/mpeg;base64,'+(await fs.readFile('assets/music/'+score.id+'.mp3')).toString('base64');
const licenses='RECORDED MUSIC\n'+await fs.readFile('assets/music/MUSIC-LICENSES.md','utf8')+'\nTHREE.JS\n'+await fs.readFile('assets/THREE-LICENSE.txt','utf8')+'\nSPACE GROTESK\n'+await fs.readFile('assets/SPACE-GROTESK-LICENSE.txt','utf8');
const result=await build({entryPoints:['src/app.js'],bundle:true,minify:true,format:'iife',target:['es2020'],write:false,legalComments:'eof'});
const js=result.outputFiles[0].text.replaceAll('</script','<\\/script');
const font=await fs.readFile('assets/space-grotesk.ttf');
const format=font.subarray(0,4).toString()==='wOF2'?'woff2':font.subarray(0,4).toString()==='wOFF'?'woff':'truetype';
const css=(await fs.readFile('src/style.css','utf8'))+'\n'+(await fs.readFile('src/life.css','utf8'))+'\n'+(await fs.readFile('src/readable.css','utf8'))+'\n'+(await fs.readFile('src/journey.css','utf8'))+'\n'+(await fs.readFile('src/capital.css','utf8'))+'\n'+(await fs.readFile('src/redesign.css','utf8'))+'\n'+(await fs.readFile('src/bold.css','utf8'))+'\n'+(await fs.readFile('src/contrast.css','utf8'))+'\n'+(await fs.readFile('src/v7.css','utf8'))+'\n'+(await fs.readFile('src/v8.css','utf8'))+'\n'+(await fs.readFile('src/intro.css','utf8'))+'\n'+(await fs.readFile('src/v9.css','utf8'))+'\n'+(await fs.readFile('src/v12.css','utf8'));
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=5,viewport-fit=cover"><meta name="theme-color" content="#b8d7e9"><meta name="description" content="Start with $100. Swipe through endless investment opportunities, discover rare 3D estates, and build your own story. A fictional, virtual-money game."><title>Broke to Billionaire: The $100 Start</title><style>@font-face{font-family:'Space Grotesk';font-style:normal;font-weight:400 700;font-display:swap;src:url(data:font/${format};base64,${font.toString('base64')}) format('${format}')}\n${css}</style></head><body><div id="app"></div><div class="loading-screen" id="loading"><div><strong>Broke to Billionaire</strong><small>正在打开城市、音乐和你的下一条街。</small><div class="loading-line"></div></div></div><script>/* Publisher configuration. Never place a server API key here. */\nwindow.UPSHIFT_CONFIG=${JSON.stringify(cfg)};window.UPSHIFT_AUDIO=${JSON.stringify(audio)};window.UPSHIFT_ART=${JSON.stringify(art)};</script><script>${js}</script><!-- Third-party licenses\n${licenses.replaceAll('--','—')}\n--></body></html>`;
await fs.mkdir(folder,{recursive:true});await fs.writeFile(folder+'/index.html',html);await fs.writeFile(folder+'/LICENSES.txt',licenses);await fs.copyFile('assets/music/LICENSE-PROVENANCE.json',folder+'/MUSIC-SOURCES.json');
await fs.copyFile('assets/music/ORIGINAL-SCORES.json',folder+'/ORIGINAL-SCORES.json');
await fs.copyFile('assets/music/CITY-CREDITS.json',folder+'/CITY-MUSIC-CREDITS.json');
console.log(`Built ${folder}/index.html: ${(Buffer.byteLength(html)/1024).toFixed(1)} KB. Embedded font: ${format}. All game assets offline.`);
