import fs from 'node:fs/promises';
import {build,transform} from 'esbuild';
const cfg=JSON.parse(await fs.readFile('config.json','utf8'));
const production=process.argv.includes('--production');
if(production)cfg.allowDeveloperMode=false;
const folder=production?'build/production':'build/development';
const audio={}; // Round 9: music is written as lazy script packs (music-pack/<id>.js), NOT inlined, so index.html loads fast on phones.
const musicIds=[];for(const score of JSON.parse(await fs.readFile('assets/music/CITY-CREDITS.json','utf8')))musicIds.push(score.id);
const art={};for(const city of ['taipei','tokyo','vegas','singapore','newyork','monaco','luxury-texture','ivory-texture','ui-taipei','ui-tokyo','ui-vegas','ui-singapore','ui-newyork','ui-monaco','logo','cg-poor','cg-rich','menu-bg'])art[city]='data:image/webp;base64,'+(await fs.readFile('assets/art/'+city+'.webp')).toString('base64');
for(const f of await fs.readdir('assets/art/ic'))if(f.endsWith('.webp'))art['ic-'+f.replace('.webp','')]='data:image/webp;base64,'+(await fs.readFile('assets/art/ic/'+f)).toString('base64');
for(const f of await fs.readdir('assets/art/mg'))if(f.endsWith('.webp'))art['mg-'+f.replace('.webp','')]='data:image/webp;base64,'+(await fs.readFile('assets/art/mg/'+f)).toString('base64');
const scores=JSON.parse(await fs.readFile('assets/music/ORIGINAL-SCORES.json','utf8'));for(const score of scores)musicIds.push(score.id);
await fs.mkdir('music-pack',{recursive:true});
for(const id of musicIds){const body='(window.UPSHIFT_AUDIO=window.UPSHIFT_AUDIO||{})['+JSON.stringify(id)+']="data:audio/mpeg;base64,'+(await fs.readFile('assets/music/'+id+'.mp3')).toString('base64')+'";window.dispatchEvent(new CustomEvent("upshift-audio",{detail:'+JSON.stringify(id)+'}));';let old='';try{old=await fs.readFile('music-pack/'+id+'.js','utf8');}catch{}if(old!==body)await fs.writeFile('music-pack/'+id+'.js',body);}
const licenses='RECORDED MUSIC\n'+await fs.readFile('assets/music/MUSIC-LICENSES.md','utf8')+'\nTHREE.JS\n'+await fs.readFile('assets/THREE-LICENSE.txt','utf8')+'\nSPACE GROTESK\n'+await fs.readFile('assets/SPACE-GROTESK-LICENSE.txt','utf8');
const result=await build({entryPoints:['src/app.js'],bundle:true,minify:true,format:'iife',target:['es2020'],write:false,legalComments:'eof'});
const js=result.outputFiles[0].text.replaceAll('</script','<\\/script');
const font=await fs.readFile('assets/space-grotesk.woff2'); // R13: lossless WOFF2 (was 137 KB TTF)
const format=font.subarray(0,4).toString()==='wOF2'?'woff2':font.subarray(0,4).toString()==='wOFF'?'woff':'truetype';
const css=(await fs.readFile('src/style.css','utf8'))+'\n'+(await fs.readFile('src/life.css','utf8'))+'\n'+(await fs.readFile('src/readable.css','utf8'))+'\n'+(await fs.readFile('src/journey.css','utf8'))+'\n'+(await fs.readFile('src/capital.css','utf8'))+'\n'+(await fs.readFile('src/redesign.css','utf8'))+'\n'+(await fs.readFile('src/bold.css','utf8'))+'\n'+(await fs.readFile('src/contrast.css','utf8'))+'\n'+(await fs.readFile('src/v7.css','utf8'))+'\n'+(await fs.readFile('src/v8.css','utf8'))+'\n'+(await fs.readFile('src/intro.css','utf8'))+'\n'+(await fs.readFile('src/v9.css','utf8'))+'\n'+(await fs.readFile('src/v12.css','utf8'))+'\n'+(await fs.readFile('src/r9.css','utf8'))+'\n'+(await fs.readFile('src/r11.css','utf8'))+'\n'+(await fs.readFile('src/r12.css','utf8'))+'\n'+(await fs.readFile('src/r13.css','utf8'));
const cssMin=(await transform(css,{loader:'css',minify:true,logLevel:'error'})).code; // R13: minified CSS for faster first load
const LATE=new Set(['taipei','ui-taipei','ic-frame0','ic-frame1','ic-frame2','ic-frame3','ic-frame4','ic-frame5','tokyo','vegas','singapore','newyork','monaco','ui-tokyo','ui-vegas','ui-singapore','ui-newyork','ui-monaco','cg-poor','cg-rich','logo','luxury-texture','ivory-texture']);const artEarly={},artLate={};for(const [k,v] of Object.entries(art))(LATE.has(k)?artLate:artEarly)[k]=v;
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=5,viewport-fit=cover"><script>/* R11 phone layout: in landscape, phones lay the game out on a virtual ~700px-tall desktop canvas and the browser scales it to the screen, so the phone UI keeps the desktop proportions the player asked for */(function(){var m=document.querySelector('meta[name=viewport]');function fit(){var c=matchMedia('(pointer:coarse)').matches,W=screen.width,H=screen.height,S=Math.min(W,H),L=Math.max(W,H);if(!c||S>=700)return;var so=screen.orientation&&screen.orientation.type||'',land=innerWidth>innerHeight||/landscape/.test(so)&&innerWidth>=innerHeight*.9;if(!land){var pc='width=device-width,initial-scale=1,viewport-fit=cover';if(m.getAttribute('content')!==pc)m.setAttribute('content',pc);document.documentElement.removeAttribute('data-vdesk');window.__vdesk=0;return;}var vw=Math.round(Math.max(1180,700*L/S));var nc='width='+vw+',user-scalable=no,viewport-fit=cover';if(m.getAttribute('content')!==nc)m.setAttribute('content',nc);document.documentElement.setAttribute('data-vdesk','1');window.__vdesk=1;}fit();var tm;addEventListener('orientationchange',function(){setTimeout(function(){fit();dispatchEvent(new Event('resize'));},250);});addEventListener('resize',function(){clearTimeout(tm);tm=setTimeout(fit,300);});})();</script><meta name="theme-color" content="#b8d7e9"><meta name="description" content="Start with $100. Swipe through endless investment opportunities, discover rare 3D estates, and build your own story. A fictional, virtual-money game."><title>Broke to Billionaire: The $100 Start</title><style>@font-face{font-family:'Space Grotesk';font-style:normal;font-weight:400 700;font-display:swap;src:url(data:font/${format};base64,${font.toString('base64')}) format('${format}')}\n${cssMin}</style></head><body><div id="app"></div><div class="loading-screen" id="loading"><div><strong>Broke to Billionaire</strong><small>Loading…</small><div class="loading-line"></div></div></div><script>/* Publisher configuration. Never place a server API key here. */\nwindow.UPSHIFT_CONFIG=${JSON.stringify(cfg)};window.UPSHIFT_AUDIO=${JSON.stringify(audio)};window.UPSHIFT_ART=${JSON.stringify(artEarly)};</script><script>${js}</script><script>/* R13 fast start: big late-game art arrives after the game has booted */Object.assign(window.UPSHIFT_ART,${JSON.stringify(artLate)});window.dispatchEvent(new Event('upshift-art'));</script><!-- Third-party licenses\n${licenses.replaceAll('--','—')}\n--></body></html>`;
await fs.mkdir(folder,{recursive:true});await fs.writeFile(folder+'/index.html',html);await fs.writeFile(folder+'/LICENSES.txt',licenses);await fs.copyFile('assets/music/LICENSE-PROVENANCE.json',folder+'/MUSIC-SOURCES.json');
await fs.copyFile('assets/music/ORIGINAL-SCORES.json',folder+'/ORIGINAL-SCORES.json');
await fs.copyFile('assets/music/CITY-CREDITS.json',folder+'/CITY-MUSIC-CREDITS.json');
console.log(`Built ${folder}/index.html: ${(Buffer.byteLength(html)/1024).toFixed(1)} KB. Embedded font: ${format}. All game assets offline.`);
