# Merge tools/i18n/b*.txt (idx|English) with tools/i18n-keys.json into src/i18n-en.js
import json,glob,re
keys=list(json.load(open('tools/i18n-keys.json')))
tr={}
for f in sorted(glob.glob('tools/i18n/b*.txt')):
    for ln in open(f,encoding='utf8'):
        ln=ln.rstrip('\n')
        if not ln.strip():continue
        i,_,e=ln.partition('|');tr[int(i)]=e
def dec(s):
    return re.sub(r'\\(.)',lambda m:{'n':'\n','t':' '}.get(m.group(1),m.group(1)),s)
pairs=[];bad=0
for i,k in enumerate(keys):
    e=tr.get(i)
    if e is None: continue
    zk,ev=dec(k),dec(e)
    if zk.count('{}')!=ev.count('{}'): bad+=1;print('placeholder mismatch',i,k,'|',e)
    pairs.append([zk,ev])
open('src/i18n-en.js','w',encoding='utf8').write('// generated by tools/i18n-build.py — edit tools/i18n/*.txt\nexport default '+json.dumps(pairs,ensure_ascii=False,separators=(',',':'))+';\n')
print(len(pairs),'pairs',bad,'mismatches')
# extra hand-written zh|en pairs (templates allowed)
import os
if os.path.exists('tools/i18n/extra.txt'):
    for ln in open('tools/i18n/extra.txt',encoding='utf8'):
        ln=ln.rstrip('\n')
        if '|' in ln and not ln.startswith('#'):
            z,_,e=ln.partition('|');pairs.append([dec(z),dec(e)])
    open('src/i18n-en.js','w',encoding='utf8').write('// generated by tools/i18n-build.py — edit tools/i18n/*.txt\nexport default '+json.dumps(pairs,ensure_ascii=False,separators=(',',':'))+';\n')
    print('with extras',len(pairs))
