import {LifeUI as JourneyUI} from './journey-ui.js';
import {glyph} from './life-ui.js';
import {escape as safe} from './ui.js';
import {CLASSES,getCity,owns,finishRest,restActivity} from './life-core.js';
import {makeOffer,markPeak} from './engine.js';
import {worth,lateTier,TIERS_LATE,FACTIONS,ensureEstate,reconcile,billQuote,restDue,pendingEvent,eventView,resolveEvent,acknowledgeEvent,securityOdds,hireGuards,activeGuards,healthRisk,medicalOptions,buyMedical,regions,currentRegion,enterRegion,luxuries,consumeLuxury,PERKS,initLegacy,buyPerk,collectLegacy} from './endgame-core.js';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n/100);
const short=n=>n>=1e10?'$'+(n/1e10).toFixed(2)+'亿':n>=1e6?'$'+(n/1e6).toFixed(1)+'万':money(n);
const clock=n=>Math.floor(Math.max(0,n)/60000).toString().padStart(2,'0')+':'+Math.ceil(Math.max(0,n)/1000%60).toString().padStart(2,'0');
const btn=(id,text,v='',disabled=false,cls='')=>`<button class="life-button ${cls}" data-action="life-${id}" data-value="${v}" ${disabled?'disabled':''}>${text}</button>`;
export class LifeUI extends JourneyUI{
 constructor(c){super(c);this.contextExpanded=false;this.eventBusy=false;this.nextLateTick=0;this.eventOpened='';this.c.meta().wealthTextures??=true;for(const name of ['luxury','ivory'])document.documentElement.style.setProperty('--'+name+'-material',`url('${window.UPSHIFT_ART?.[name+'-texture']||''}')`);initLegacy(this.c.meta());
  $('menu-button').classList.add('global-menu');$('game').append($('menu-button'));
  $('energy-hud').insertAdjacentHTML('afterend',`<button id="capital-summary" class="capital-summary" data-action="life-status" hidden></button>`);
  this.settings.scale=Math.max(.75,Math.min(1.25,this.settings.scale));this.applyUI();
 }
 get e(){return this.s.estate||ensureEstate(this.s);}
 hasPendingDeath(){return this.s.ended&&!!pendingEvent(this.s)?.resolved;}
 renderHud(){super.renderHud();if(!$('capital-summary'))return;const s=this.s,e=this.e,t=reconcile(s),inGame=this.c.started?.()!==false,g=$('game'),m=this.c.meta();g.dataset.capitalTier=t;g.dataset.wealthTextures=m.wealthTextures?'on':'off';g.dataset.legacySkin=m.legacy?.skin||'default';document.body.dataset.legacySkin=m.legacy?.skin||'default';
  $('city-panorama').hidden=!inGame||t===0||!!s.life.travel;
  $('class-ticker').hidden=!inGame||t<3||!!s.life.travel;
  $('life-map-pull').hidden=!inGame||t===0||!!s.life.rest||!!s.life.travel;
  $('ui-tools').hidden=true;$('rest-scene-tools').hidden=true;$('life-rest-caption').hidden=true;$('life-hex').hidden=true;
  const cv=$('cash-value');cv.style.fontSize=(innerWidth<900?(cv.textContent.length>8?19:25):(cv.textContent.length>8?23:29))+'px';
  const summary=$('capital-summary');summary.hidden=!inGame||t<2||!!s.life.travel;
  if(!summary.hidden){const locked=s.life.rest&&!s.life.rest.paid,q=locked?{total:restDue(s.life.rest)}:billQuote(s);summary.innerHTML=`<span>${TIERS_LATE[t].name} · 总身家 ${short(worth(s))}</span><b>${locked?'本次账单':'下次休息'} ${short(q.total)} <i>ⓘ</i></b>`;summary.title='查看总身家、预计账单、健康和当前机制';}
  if(t<2){const h=$('energy-hint');h.textContent=s.life.rest?'假期恢复中':h.textContent.split('·')[0].trim()+' · 下休 '+short(billQuote(s).total);}
  if(s.life.rest)this.paintNews();
  this.paintContext();
 }
 paintContext(){super.paintContext();const el=$('project-context');if(!el||el.hidden)return;const detail=el.querySelector('p');if(detail){detail.id='culture-detail';detail.hidden=!this.contextExpanded;}const h=el.querySelector('h2');if(h){const name=h.textContent;h.innerHTML=`<span>${safe(name)}</span><button data-action="life-culture" aria-label="${this.contextExpanded?'收起':'展开'}当地项目说明" aria-expanded="${this.contextExpanded}" aria-controls="culture-detail">${this.contextExpanded?'−':'i'}</button>`;}el.classList.toggle('expanded',this.contextExpanded);}
 paintNews(){super.paintNews();const el=$('world-news');if(!el||el.hidden)return;el.classList.add('compact-news');el.querySelector('.news-kicker').textContent='世界新闻 · 游戏事件';if(!el.querySelector('button'))el.insertAdjacentHTML('beforeend',btn('news','查看新闻 →'));}
 interceptDock(){if(this.s.offer.type==='world-event'&&!this.s.life.rest&&!this.s.life.travel){this.renderStreetEvent();return true;}return super.interceptDock();}
 renderStreetEvent(){const ev=this.s.estate.queue.find(x=>x.id===this.s.offer.eventId),d=$('game-dock');d.dataset.kind='world-event';d.innerHTML=`<span class="life-eyebrow">CITY ENCOUNTER / 街头会面</span><h1>${ev?safe(eventView(this.s,ev).title):'会面已结束。'}</h1><p class="small-rule">${ev?.ack?'这段插曲已记录。继续探索下一条街。':'用几个选择回应这段插曲，不需要打开复杂管理面板。'}</p>${ev?.ack?'<button class="primary" data-action="next">继续前行 →</button>':btn('open-event','回应这次会面 →','',false,'primary')}`;this.paintContext();this.c.fit();}
 beforeNext(){if(pendingEvent(this.s)){this.openEvent();return false;}this.contextExpanded=false;return super.beforeNext();}
 openEvent(){const ev=pendingEvent(this.s);if(!ev||this.c.started?.()===false||this.c.busy?.())return;const modal=this.c.modal?.();if(modal&&modal!=='world-event')return;const v=eventView(this.s,ev),result=ev.result;this.eventOpened=ev.id;
  const tag=ev.kind==='health'?'♥':ev.kind==='security'?'◇':ev.kind==='luxury'?'✦':ev.kind==='tax'?'§':ev.kind==='scandal'?'!':FACTIONS.find(f=>f.id===ev.faction)?.symbol||'↗';
  this.c.open('world-event','','',`<div class="event-dialog ${ev.kind} ${ev.resolved?'resolved':''}"><div class="event-dialog-top"><span>${safe(v.tag)}</span><small>${getCity(this.s).name}</small></div><div class="event-dialog-symbol">${tag}</div><h2 id="modal-title">${safe(v.title)}</h2><p>${safe(v.body)}</p>${ev.kind==='health'?`<div class="health-slots">${Array.from({length:this.e.maxHealth},(_,i)=>`<span class="${i<this.e.health?'alive':'spent'}">♥</span>`).join('')}<small>衰退 ${ev.risk}%</small></div>`:''}${ev.resolved?`${result?.delta?`<div class="event-cash ${result.delta<0?'loss':''}">${result.delta>0?'+':'−'}${money(Math.abs(result.delta))}</div>`:''}<button class="primary" data-action="life-event-ack" data-value="${ev.id}">${this.s.ended?'进入人生结算':'记下了，继续 →'}</button>`:`<div class="dialog-choices">${v.choices.map(o=>`<button data-action="life-event-choice" data-value="${ev.id}:${o.id}" ${o.cost>0&&o.cost>=this.s.cash?'disabled':''}><div><strong>${safe(o.label)}</strong><b>${o.cost?money(o.cost):'不预付'}</b></div><span>${safe(o.detail)}</span>${o.penalty?`<small>后果可能扣除 ${money(o.penalty)}</small>`:''}</button>`).join('')}</div><div class="event-dialog-foot">现金 ${money(this.s.cash)} · 每个选择只结算一次</div>`}</div>`,{custom:true,noClose:true});
 }
 renderRest(){const s=this.s,r=s.life.rest;if(!r)return;const d=$('game-dock'),c=CLASSES[r.class],pending=pendingEvent(s),due=restDue(r),q=r.bill||billQuote(s);d.dataset.kind='rest';const activities=r.activities.filter(x=>!x.instant),instant=r.activities.find(x=>x.instant);
  const tile=a=>`<article class="rest-choice"><span>${({drink:'☕',read:'▤',stretch:'↟',massage:'✦',lounge:'☀',sleep:'☾',toast:'♧'})[a.pose]}</span><div><strong>${safe(a.name)}</strong><small>减少 ${Math.floor(a.seconds/60)} 分 ${a.seconds%60} 秒</small></div>${btn('activity',a.used?'已体验':short(a.price),a.id,a.used||s.cash<=a.price||r.remaining<=0||!!pending)}</article>`;
  d.innerHTML=`<div class="rest-compact-title"><span>休息 / ${c.name}</span><button data-action="life-status" aria-label="查看完整身家与账单">ⓘ</button></div><h1>${r.paid?'让身体跟上你的野心。':'先付账单，再谈人生。'}</h1><div class="rest-worth"><span>当前总身家 <b>${short(worth(s))}</b></span><span>可用现金 <b>${short(s.cash)}</b></span></div><div class="rest-progress-head"><span id="rest-status">${r.paid?'正在恢复':'账单未支付'}</span><strong id="rest-clock">${clock(r.remaining)}</strong></div><div class="rest-track" role="progressbar" aria-label="休息进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="rest-fill"></i></div>
  ${!r.paid?`<div class="bill-lines"><span>生活维护 <b>${short(r.maintenance)}</b></span><span>地区税费 <b>${short(r.tax)}</b></span><span>安保 / 管理 / 减免 <b>${r.extra<0?'−':''}${short(Math.abs(r.extra||0))}</b></span><strong>本次合计 <b>${short(due)}</b></strong></div><p class="bill-footnote">税基为入休时总身家 ${short(q.worth)}；资产不重复计算，税单入休后锁定。现金不足即结束本局，不再自动救助。</p>${pending?btn('open-event','先处理休息事件 →','',false,'primary'):btn('pay',s.cash<=due?'无法支付 · 结算本局':`支付 ${short(due)} · 开始恢复`,'',false,'primary')}`:`<div id="rest-ready" ${r.remaining>0?'hidden':''}>${btn('finish',`领取 ${s.life.energyCap} 体力，继续出发 →`,'',!!pending,'primary')}</div><div id="rest-options" ${r.remaining<=0?'hidden':''}>${activities.slice(0,2).map(tile).join('')}<div class="rest-bottom-buttons">${btn('rest-all','更多休息活动')}${lateTier(s)>=3?btn('medical','医疗 / 延寿'):''}</div>${instant?btn('instant',`立即恢复 · ${short(instant.price)}`,instant.id,s.cash<=instant.price||!!pending,'instant-button'):''}</div>`}
  <div class="rest-view-buttons">${[0,1,2].map((i)=>btn('camera',['人物','全景','侧面'][i],i,false,r.camera===i?'selected':'')).join('')}</div>`;
  this.paintRest();this.paintNews();this.c.fit();
 }
 paintRest(){const r=this.s.life.rest;if(!r||!$('rest-clock'))return;$('rest-clock').textContent=clock(r.remaining);const pct=r.paid?(1-r.remaining/r.duration)*100:0;$('rest-fill').style.width=pct+'%';$('rest-fill').parentElement.setAttribute('aria-valuenow',Math.round(pct));$('rest-status').textContent=!r.paid?'账单未支付':r.remaining<=0?'恢复完成':'离线也会继续恢复';if($('rest-ready'))$('rest-ready').hidden=r.remaining>0;if($('rest-options'))$('rest-options').hidden=r.remaining<=0;}
 openRestAll(){const r=this.s.life.rest;if(!r?.paid)return;this.c.open('rest-activities','休息，换一种方式。','活动消耗游戏币，缩短剩余计时。',`<div class="rest-all-grid">${r.activities.filter(a=>!a.instant).map(a=>`<article><h3>${safe(a.name)}</h3><p>减少 ${Math.floor(a.seconds/60)} 分 ${a.seconds%60} 秒</p>${btn('rest-do',a.used?'已体验':money(a.price),a.id,a.used||r.remaining<=0||this.s.cash<=a.price)}</article>`).join('')}</div>`);}
 openStatus(){const s=this.s,t=lateTier(s),q=s.life.rest?(s.life.rest.bill||billQuote(s)):billQuote(s),pending=s.offer.pendingStake||0,asset=worth(s)-s.cash-pending,e=this.e;this.c.open('life-status','看清自己，还剩下什么。',`${TIERS_LATE[t].name} / 所有金额都是游戏币`, `<div class="capital-ledger"><div><span>可用现金</span><b>${money(s.cash)}</b></div><div><span>资产、服装与已购商品</span><b>${money(asset)}</b></div><div><span>待交割本金（仅计一次）</span><b>${money(pending)}</b></div><div class="total"><span>当前总身家</span><b>${money(worth(s))}</b></div></div><h3>${s.life.rest?'已锁定的本次账单':'下次休息预估'}</h3><div class="capital-ledger"><div><span>生活维护</span><b>${money(q.maintenance)}</b></div><div><span>地区税 · ${(q.rate*100).toFixed(2)}%</span><b>${money(s.life.rest?.tax??q.tax)}</b></div><div><span>保镖工资</span><b>${money(q.guards)}</b></div><div><span>管理费用</span><b>${money(q.management)}</b></div><div><span>转世减免</span><b>−${money(q.credit)}</b></div><div class="total"><span>合计</span><b>${money(s.life.rest?restDue(s.life.rest):q.total)}</b></div></div><p>按当前总身家和区域估算，入休时锁定；不包含尚未触发的风波、抢劫和自选消费。没钱付剩余强制账单会直接结束本局。</p><h3>健康 ${'♥'.repeat(e.health)}${'♡'.repeat(e.maxHealth-e.health)}</h3><p>已经休息 ${e.age} 次。下一次衰退概率 ${healthRisk(s,true)}%；每次休息 +1 个百分点，抽中减少 1 格，归零死亡。</p><h3>当前可用机制</h3><p>${[['基础投资与休息',0],['城市通行与商品',1],['社群交往',2],['安保 / 地区税 / 康复',3],['财务风波 / 多派系',4],['当地奢侈消费 / 延寿',5],['工业特区',6],['主权特区',7],['细胞更新',8],['云端区域',9],['极限财富压力',10]].map(([name,at])=>`<span class="mechanism-token ${t>=at?'active':''}">${t>=at?'✓':'🔒'} ${name}</span>`).join('')}</p><p>机制按当前总身家而非历史最高身家启停。变穷后购买过的功能会暂时停用；回升后恢复，物品不会重复收费。</p>`);}
 openSecurity(){const s=this.s,e=this.e,o=securityOdds(s);this.c.open('security','有钱以后，安全也有账单。','谨慎降低遇险率，强硬提高反抗率但更容易被盯上。',`<div class="security-summary"><b>休息抢劫触发约 ${o.robbery.toFixed(0)}%</b><span>基础躲避 ${o.dodge.toFixed(0)}% · 绕路额外 +15%，上限 97%</span></div><div class="security-levels">${[0,1,2,3].map(level=>{const cost=level>e.guards?[0,100000,1000000,10000000][level]-[0,100000,1000000,10000000][e.guards]:0;return btn('guards',`<strong>${['不雇佣','随行护卫','专业小队','私人安保团'][level]}</strong><span>${e.guards===level?'已选':cost?'聘用差价 '+money(cost):'调整不退费用'} · 基础每次休息 ${money([0,35000,350000,3500000][level])}</span>`,`${level}:${e.stance}`,lateTier(s)<3||!!s.life.rest||s.life.travel||s.cash<=cost,e.guards===level?'selected':'');}).join('')}</div><h3>你的意志</h3><div class="stance-choices">${[['cautious','低调绕行','抢劫触发 −6%，躲避 +8%；工资 ×1.4'],['balanced','正常随行','标准概率与工资'],['assertive','公开威慑','抢劫触发 +5%，反抗 +14%；更引人注意']].map(([id,name,desc])=>btn('guards',`<strong>${name}</strong><span>${desc}</span>`,e.guards+':'+id,lateTier(s)<3||!!s.life.rest||!!s.life.travel,e.stance===id?'selected':'')).join('')}</div><p>跌回 $100,000 总身家以下，安保暂时停用且不收工资。所有概率都是游戏规则，不是真实安全建议。</p>`);}
 openFactions(){const t=lateTier(this.s);this.c.open('factions','财富让你被更多人看见。','关系不是永久资产，会随每次选择变化。',`<div class="faction-list">${FACTIONS.map(f=>`<article class="${t<f.at?'locked':''}"><b>${f.symbol}</b><div><h3>${f.name}</h3><p>${t<f.at?'尚未达到当前财富门槛':this.e.relations[f.id]<=-35?'敌对：可能触发惩罚':this.e.relations[f.id]>=35?'友好：可能触发馈赠':'观望：支持与拒绝都会留下记录'}</p><div class="relation-line"><i style="left:${(this.e.relations[f.id]+100)/2}%"></i></div></div><strong>${this.e.relations[f.id]>0?'+':''}${this.e.relations[f.id]}</strong></article>`).join('')}</div><p>派系会在街道和休息事件中提出请求。地下帮派严重敌对可能暗杀；议政署敌对会带来冻结与罚款，不是每个派系都使用相同惩罚。</p>`);}
 openRegions(){this.c.open('regions',getCity(this.s).name+'，还有更高的一层。','更高门槛、更高税率，也有当地专属项目。',`<div class="region-grid">${regions(this.s.life.city).map((z,i)=>`<article><span>0${i+1} / ${i?'WEALTH DISTRICT':'THE STREET'}</span><h3>${z.name}</h3><p>${z.at?'总身家门槛 '+short(z.at*100):'没有财富门槛'}<br>区域税率系数 ×${z.tax} · 项目风险 +${z.risk}</p>${btn('region',this.e.region===z.id?'当前所在':worth(this.s)<z.at*100?'尚未开放':'进入该区域',z.id,worth(this.s)<z.at*100||this.e.region===z.id)}</article>`).join('')}</div><p>当前：${currentRegion(this.s).name}。跌破区域门槛会自动回到普通街区。高空 / 轨道区域是虚构后期地点，不代表现实设施。</p>`);}
 openMedical(){this.c.open('medical','时间，开始变得很贵。',`健康 ${this.e.health}/${this.e.maxHealth} · 下一次衰退概率 ${healthRisk(this.s,true)}%`, `<div class="medical-list">${medicalOptions(this.s).map(o=>`<article><h3>${o.name}</h3><p>${o.desc}</p><span>门槛 ${short(o.min*100)} · 本次 ${short(o.cost)}</span>${btn('medical-buy','购买疗程',o.id,worth(this.s)<o.min*100||this.s.cash<=o.cost||o.id==='care'&&this.e.health>=this.e.maxHealth||!!pendingEvent(this.s))}</article>`).join('')}</div><p>累计购买会让下一次医疗更贵。不能在事件结果锁定后临时改写抽签；延寿不等于永生，也不能复活已死亡角色。</p>`);}
 openLuxury(){this.c.open('luxury',getCity(this.s).name+'的昂贵回忆。','不生息、不变现，只留下奢侈点。',`<div class="luxury-list">${luxuries(this.s).map(i=>`<article><span>EXCLUSIVE / ${getCity(this.s).name}</span><h3>${i.name}</h3><p>${short(i.price)} → <b>${i.points} 奢侈点</b></p><small>当前总身家门槛 ${short(i.at*100)}</small>${btn('luxury-buy',this.e.luxuries.includes(i.id)?'本局已消费':'消费并留下回忆',i.id,!i.available||this.s.cash<=i.price||!!this.s.life.rest||!!this.s.life.travel)}</article>`).join('')}</div><p>本局待结算：${this.e.luxuryEarned} 点。人生结束后进入转世账户，每个项目本局只消费一次。</p>`);}
 openLegacy(title=false){this.legacyFromTitle=title;const l=initLegacy(this.c.meta()),action=title?'onboard-':'life-';this.c.open('legacy','','',`<div class="legacy-panel"><div class="legacy-top"><span>AFTERLIFE ATELIER / 转世事务所</span><button data-action="${title?'onboard-legacy-back':'close'}" aria-label="返回">×</button></div><h2 id="modal-title">钱带不走，习惯可以。</h2><p>可用奢侈点 <strong>${l.points}</strong> · 累计 ${l.lifetime} · 当前人生待结算 ${this.e.luxuryEarned}</p><div class="legacy-grid">${PERKS.map(p=>{const owned=l.unlocks.includes(p.id);return `<article><span>${p.type} / ${p.cost} LP</span><h3>${p.name}</h3><p>${p.desc}</p><button class="life-button" data-action="${action}${owned&&p.type==='皮肤'?'skin':'perk'}" data-value="${p.id}" ${owned&&p.type!=='皮肤'||!owned&&l.points<p.cost?'disabled':''}>${owned?(p.type==='皮肤'?(l.skin===p.id?'正在使用':'使用皮肤'):'已解锁 · 下局生效'):'解锁 · '+p.cost+' 点'}</button></article>`;}).join('')}</div><button class="life-button" data-action="${action}skin" data-value="default">使用默认皮肤</button><p>机制只在新一局生效；皮肤立即生效。没有真实充值，客户端存档并非防作弊联网账户。</p></div>`,{custom:true,noClose:title,wide:true});}
 purchasePerk(id){try{buyPerk(this.c.meta(),id);this.c.save();this.openLegacy(this.legacyFromTitle);}catch(e){this.c.toast(e.message);}}
 chooseSkin(id){const l=initLegacy(this.c.meta());if(id!=='default'&&(!l.unlocks.includes(id)||PERKS.find(p=>p.id===id)?.type!=='皮肤'))return;l.skin=id;this.c.save();this.renderHud();this.openLegacy(this.legacyFromTitle);}
 guide(){this.c.open('life-guide','财富越高，人生越不轻松。','Last $100: Swipe to Rich / 保留 3.1 操作',`<div class="life-guide"><h3>体力与城市</h3><p>初始 200 体力，可分四次升级至 400。前进 −5、投资 −3、购买 −2、旅行 −10。昼夜随体力变化；耗尽后休息，完成后回满。六座城市各有 16 个当地项目，其中四个需要较高身家；每十步实际绕过街角，并转动镜头。城市配乐来自独立授权录音且离线内置。</p><h3>当前身家，决定生活难度</h3><p>身家＝现金＋持有资产、服装和商品的购入价＋尚未交割的本金；不是最高纪录，也不重复计算已扣的费用。机制按当前身家启停，变穷会退回简单界面。已经购买的高级服务暂时停用，重新富裕后恢复。奢侈消费不计入资产。</p><h3>强制账单</h3><p>平时显示下次休息预估，菜单可以展开明细。入休时锁定维护、地区税、保镖工资和管理费用；事件可能另行扣款或奖励。先完成事件，再交账单。现金无法覆盖账单并保留一美分，即结束本局；没有公共救助。已缴费后免费等待十分钟，或选择付费活动缩短时间。高层地区税率更高，拒税会损害议政署关系。</p><h3>健康与简单选择</h3><p>初始健康 5 格、衰退概率 0%。每次休息概率增加 1 个百分点，第一次为 1%；抽中只减少一格，归零死亡。体检和危险事件在触发时锁定抽签，刷新不会重抽。高财富可购买康复与延寿。财务风波分三次简单选项：完成合规有奖励，中途拒绝有巨额罚款。</p><h3>派系与安保</h3><p>达到门槛后出现社群、科技、工业、议政署、地下帮派和资本公会。捐赠、合作、拒绝都会影响关系；好友可能回馈，敌对者可能冻结财产或报复。保镖和你选择的安保姿态影响劫案与躲避；地下暗杀失败会死亡，不是普通投资亏损。</p><h3>只消费，不生息</h3><p>地区奢侈品只消耗游戏币、奖励奢侈点，没有现金收益；本局结束或主动重开后，点数一次性转入转世事务所。机制解锁在下局生效，皮肤可以立即换。每次死亡都会保存到本机人生排行榜，不是联网全球榜。</p><h3>稀有街区与投资</h3><p>地区邀请是进入或离开的选择，不是投资。进入后直到体力耗尽，只做当地工作：稳妥工作 −8 体力拿固定报酬；大胆尝试 −12，65% 获得 2.3 倍，否则 0.35 倍基础报酬。普通投资失败只损失投入；东京与纽约有双重审核，新加坡有延迟交割。街头项目最高 $500，高级项目 $1,000–$100,000，顶级项目 $100,000 起。系统金额安全上限 9 万亿美元，路线无最终站。</p><h3>可读性与保存</h3><p>主菜单「界面与文字」调整面板 75%–125%、文字 14–22px；财富材质也可在主菜单关闭。世界地图直接点击，不需要拖拉。手机面板内容可上下滚动，场景独立占位。电脑和手机分别存档，同一浏览器地址下自动保存；清除浏览器数据会清除进度。所有事件、健康概率和税制均为虚构游戏规则，无充值、兑现或医疗投资建议。</p></div>`);}
 menuExtras(){const t=lateTier(this.s);return super.menuExtras()+`<section class="capital-menu"><div class="life-eyebrow">LIFE HAS CONSEQUENCES / 人生的后半程</div><div class="capital-menu-grid">${btn('status','身家与下期账单')}${btn('legacy','转世事务所 · '+(this.c.meta().legacy?.points||0)+' LP')}${t>=2?btn('factions','派系关系'):''}${t>=3?btn('security','雇佣保镖 / 安保姿态')+btn('medical','健康 / 昂贵延寿'):''}${t>=4?btn('regions','城市深层区域'):''}${t>=5?btn('luxury','地区奢侈消费'):''}${btn('textures','财富配色与贴图：'+(this.c.meta().wealthTextures?'开启':'关闭'))}</div><p>功能按当前总身家启停。最贫穷阶段没有额外常驻面板；必要的健康与账单只在休息弹窗出现。</p></section>`;}
 tick(){super.tick();if(this.c.started?.()===false)return;const now=performance.now();if(now<this.nextLateTick)return;this.nextLateTick=now+300;if(pendingEvent(this.s)&&!this.c.modal?.()&&!this.c.busy?.()&&(!this.s.ended||pendingEvent(this.s)?.resolved))this.openEvent();}
 async handle(a,v){
  const actions=['culture','open-event','event-choice','event-ack','status','security','guards','factions','regions','region','medical','medical-buy','luxury','luxury-buy','legacy','perk','skin','textures','rest-all','rest-do','news'];
  if(!a.startsWith('life-')||!actions.includes(a.slice(5)))return super.handle(a,v);
  try{switch(a.slice(5)){
   case 'culture':this.contextExpanded=!this.contextExpanded;this.paintContext();break;
   case 'open-event':this.openEvent();break;
   case 'event-choice':{if(this.eventBusy)break;this.eventBusy=true;try{const [id,choice]=v.split(':');document.querySelectorAll('.dialog-choices button').forEach(b=>b.disabled=true);if(pendingEvent(this.s)?.kind==='health'){document.querySelector('.event-dialog')?.classList.add('drawing');await new Promise(r=>setTimeout(r,this.c.motion?.()===false?0:650));}resolveEvent(this.s,id,choice);markPeak(this.s);this.c.save();this.c.refresh();this.openEvent();}finally{this.eventBusy=false;}break;}
   case 'event-ack':acknowledgeEvent(this.s,v);this.c.save();this.c.close();if(this.s.ended)this.c.onDeath();else{this.c.refresh();this.c.renderDock();if(pendingEvent(this.s))this.openEvent();}break;
   case 'status':this.openStatus();break;case 'security':this.openSecurity();break;case 'factions':this.openFactions();break;case 'regions':this.openRegions();break;case 'medical':this.openMedical();break;case 'luxury':this.openLuxury();break;
   case 'guards':{const [level,stance]=v.split(':');hireGuards(this.s,Number(level),stance);this.persist();this.openSecurity();break;}
   case 'region':{const z=enterRegion(this.s,v);this.c.close();this.s.offer=makeOffer(this.s);this.s.lastResult=null;this.c.world.setOffer(this.s.offer);this.persist();this.c.renderDock();this.c.toast('进入 '+z.name+'；下一次账单已按该区重算。');break;}
   case 'medical-buy':{const o=medicalOptions(this.s).find(x=>x.id===v);this.c.confirm('购买 '+o.name+'？',`立即消费 ${money(o.cost)} 游戏币。${o.desc}`,()=>{try{buyMedical(this.s,v);this.persist();this.c.renderDock();this.openMedical();}catch(e){this.c.toast(e.message);}});break;}
   case 'luxury-buy':{const o=luxuries(this.s).find(x=>x.id===v);this.c.confirm('这笔钱不会再回来。',`消费 ${money(o.price)} 获得 ${o.points} 奢侈点，不增加资产与现金收益。`,()=>{try{consumeLuxury(this.s,v);this.persist();this.c.renderDock();this.openLuxury();}catch(e){this.c.toast(e.message);}});break;}
   case 'legacy':this.openLegacy(false);break;case 'perk':this.purchasePerk(v);break;case 'skin':this.chooseSkin(v);break;
   case 'textures':this.c.meta().wealthTextures=!this.c.meta().wealthTextures;this.c.save();this.renderHud();document.querySelectorAll('[data-action="life-textures"]').forEach(b=>b.textContent='财富配色与贴图：'+(this.c.meta().wealthTextures?'开启':'关闭'));this.c.toast('财富贴图与配色已'+(this.c.meta().wealthTextures?'开启':'关闭')+'，布局不会改变。');break;
   case 'rest-all':this.openRestAll();break;case 'rest-do':restActivity(this.s,Number(v));this.persist();this.renderRest();this.openRestAll();break;
   case 'news':{const el=$('world-news');this.c.open('news','世界的另一面。','这些是会影响下一轮项目的虚构游戏新闻。',`<h3>${safe(el.querySelector('h3')?.textContent||'市场平稳')}</h3><p>${safe(el.querySelector('p')?.textContent||'')}</p>`);break;}
  }}catch(e){this.c.toast(e.message||'此操作当前不可用。');}
  return true;
 }
}
