export class Effects {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.parts=[];this.motion=true;this.low=false;this.muted=false;this.sound=true;this.last=performance.now();this.resize=()=>{const d=Math.min(devicePixelRatio,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d;this.ctx.setTransform(d,0,0,d,0,0);};window.addEventListener('resize',this.resize);this.resize();this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);}
 get muted(){return this._muted||false;}
 set muted(value){this._muted=!!value;if(value)this.audio?.suspend().catch(()=>{});else if(this.audio&&this.sound)this.audio.resume().catch(()=>{});}
 unlock(){if(!this.sound||this.muted)return;try{this.audio??=new(window.AudioContext||window.webkitAudioContext)();if(this.audio.state==='suspended')this.audio.resume().catch(()=>{});}catch{}}
 tone(kind='tap',rarity=0){if(!this.sound||this.muted)return;this.unlock();if(!this.audio)return;const notes=kind==='win'?[523,659,784,...(rarity>=3?[1047,1318]:[])]:kind==='loss'?[294,246]:kind==='rare'?[440,554,659,880]:kind==='buy'?[392,494,587,784]:[440];const now=this.audio.currentTime;
  notes.forEach((freq,i)=>{const o=this.audio.createOscillator(),gain=this.audio.createGain();o.type=kind==='loss'?'sine':'triangle';o.frequency.value=freq;const start=now+i*.065;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.013,start+.008);gain.gain.exponentialRampToValueAtTime(.0001,start+.32);o.connect(gain);gain.connect(this.audio.destination);o.start(start);o.stop(start+.35);});
 }
 burst(x,y,level=1,color='#d9c373'){
  if(!this.motion)return;const count=Math.min(this.low?40:170,35+level*24);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*(180+level*15);this.parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:1.2+Math.random()*1.5,max:2.7,r:2+Math.random()*4,angle:Math.random()*6,spin:(Math.random()-.5)*9,color:i%3===0?'#eaf2d0':i%5===0?'#b8d797':color,coin:i%4===0});}this.parts=this.parts.slice(-350);
 }
 pop(text,sub,rect,negative=false){const div=document.createElement('div');div.className='money-pop'+(negative?' negative':'');div.style.left=rect.left+rect.width*.51+'px';div.style.top=rect.top+rect.height*.47+'px';div.textContent=text;const small=document.createElement('small');small.textContent=sub;div.appendChild(small);document.body.appendChild(div);setTimeout(()=>div.remove(),this.motion?1900:900);}
 loop(now){requestAnimationFrame(this.loop);const dt=Math.min(.04,(now-this.last)/1000);this.last=now;this.ctx.clearRect(0,0,innerWidth,innerHeight);if(!this.motion||document.hidden){this.parts=[];return;}this.parts=this.parts.filter(p=>p.life>0);for(const p of this.parts){p.life-=dt;p.vy+=150*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.angle+=p.spin*dt;const c=this.ctx;c.save();c.globalAlpha=Math.min(1,p.life);c.translate(p.x,p.y);c.rotate(p.angle);c.fillStyle=p.color;if(p.coin){c.beginPath();c.ellipse(0,0,p.r,p.r*1.3,0,0,Math.PI*2);c.fill();c.strokeStyle='#fff5c388';c.lineWidth=.8;c.stroke();}else c.fillRect(-p.r/2,-p.r,p.r,p.r*1.5);c.restore();}}
}
