import {escape as safe} from './ui.js';
import {LifeUI as BaseLifeUI,glyph} from './life-ui.js';
import {getCity,CITY_DATA,CLASSES,classIndex,owns,upgradeEnergy,beginRest} from './life-core.js';
import {makeOffer,markPeak} from './engine.js';
import {DISTRICTS,CLASS_FEEDS,NEWS,LOCAL_PROJECTS,localById,phase,districtOffer,districtReward} from './city-content.js';
import {LAND_PATH} from './world-map.js';
import CITY_CREDITS from '../assets/music/CITY-CREDITS.json';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n/100);
const button=(id,text,v='',disabled=false,cls='')=>`<button class="life-button ${cls}" data-action="life-${id}" data-value="${v}" ${disabled?'disabled':''}>${text}</button>`;
const plane=`<svg viewBox="0 0 900 550" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><linearGradient id="flight-sky" x2="0" y2="1"><stop stop-color="#173c6f"/><stop offset="1" stop-color="#bce2ee"/></linearGradient><radialGradient id="flight-sun"><stop stop-color="#fff2c4"/><stop offset="1" stop-color="#fff2c400"/></radialGradient></defs><path fill="url(#flight-sky)" d="M0 0h900v550H0z"/><circle fill="url(#flight-sun)" cx="680" cy="150" r="200"/><g class="flight-clouds far" fill="#d4e9ed"><path d="M-500 520Q-450 360-340 435Q-240 310-120 425Q10 330 140 445Q270 340 400 430Q530 310 670 425Q800 335 1000 420V650H-500Z"/></g><g class="jet-wing"><path d="M-30 600L580 245L690 212L660 246L451 388L843 440L869 472L401 438L220 598Z" fill="#e4edf0" stroke="#a4b8c8" stroke-width="2"/><path d="M220 598L401 438L869 472L843 482L424 456L288 599Z" fill="#7e97b0"/><path d="M580 245L610 190L690 212L660 246Z" fill="#d4ac5f"/><path d="M362 419L571 271M424 426L619 273M486 431L657 286" stroke="#a1b5c4" stroke-width="2"/></g><g class="flight-clouds near" fill="#f4f6f1" opacity=".86"><ellipse cx="110" cy="510" rx="180" ry="60"/><ellipse cx="330" cy="580" rx="210" ry="100"/><ellipse cx="1000" cy="500" rx="150" ry="55"/></g></svg>`;
export class LifeUI extends BaseLifeUI{
 constructor(c){super(c);this.settings={scale:1,text:16};try{Object.assign(this.settings,JSON.parse(localStorage.getItem('last100-ui')||'{}'));}catch{}this.settings.scale=Math.max(.75,Math.min(1.25,Number(this.settings.scale)||1));this.settings.text=Math.max(14,Math.min(22,Number(this.settings.text)||16));
  $('game').insertAdjacentHTML('beforeend',`<aside id="city-panorama" class="city-panorama"></aside><aside id="project-context" class="project-context" hidden></aside><div id="class-ticker" class="class-ticker"></div><aside id="world-news" class="world-news" hidden></aside><div class="ui-tools" id="ui-tools"><span>UI</span><button data-action="life-scale" data-value="-0.05" aria-label="缩小界面">−</button><output id="ui-scale-label">100%</output><button data-action="life-scale" data-value="0.05" aria-label="放大界面">＋</button><button data-action="life-ui-settings" aria-label="字体与界面设置">Aa</button></div>`);
  this.c.world.onProjectPosition=(x,y)=>{const el=$('project-context');if(!el||el.hidden)return;if(innerWidth<900){el.style.left='';el.style.top='';return;}const box=el.getBoundingClientRect(),dock=$('game-dock').getBoundingClientRect();const lo=innerWidth>1200?320:285,hi=Math.max(lo,dock.left-box.width-22);el.style.left=(Math.max(lo,Math.min(hi,x-box.width/2))/this.settings.scale)+'px';el.style.top=(Math.max(90,Math.min(innerHeight-box.height-95,y-box.height-28))/this.settings.scale)+'px';};
  this.applyUI();
 }
 applyUI(){document.documentElement.style.setProperty('--ui-scale',this.settings.scale);document.documentElement.style.setProperty('--read-size',this.settings.text+'px');if($('ui-scale-label'))$('ui-scale-label').textContent=Math.round(this.settings.scale*100)+'%';try{localStorage.setItem('last100-ui',JSON.stringify(this.settings));}catch{}this.c.fit();}
 uiSettings(){this.c.open('ui-settings','界面，按你的习惯来。','3.1 布局 · 独立调整面板和文字',`<section class="read-settings"><h3>面板大小 ${Math.round(this.settings.scale*100)}%</h3><div>${button('scale','− 缩小','-0.05')}${button('scale','＋ 放大','0.05')}${button('reset-ui','恢复默认')}</div><h3>文字大小 ${this.settings.text}px</h3><div>${button('font','A−','-1')}${button('font','A＋','1')}</div><p>面板范围 75%–125%，正文范围 14–22px。设置自动保存；不会改变游戏数值。</p></section>`);}
 renderHud(){super.renderHud();if(!$('city-panorama'))return;const s=this.s,l=s.life,city=getCity(s),cl=classIndex(s),active=this.c.started?.()!==false;
  $('game').dataset.chapter=l.district?'festival':'street';$('game').dataset.time=phase(l.energy,l.energyCap);$('energy-hud').querySelector('span>small').textContent='/ '+l.energyCap;$('energy-fill').style.width=(l.energy/l.energyCap*100)+'%';$('energy-hint').textContent=l.rest?'正在恢复':`${phase(l.energy,l.energyCap)} · 前进 −5`;
  if(this.lastRunId!==s.id){this.lastRunId=s.id;this.c.world.blockAngle=(l.lastCorner||0)*Math.PI/2;this.c.world.resize();}this.c.world.setDaylight(l.energy,l.energyCap);
  const card=$('city-panorama'),key=[city.id,l.rest?.class,l.district?.city,phase(l.energy,l.energyCap),cl].join(':');card.hidden=!active||!!l.travel;if(card.dataset.key!==key){card.dataset.key=key;card.innerHTML=`<div class="panorama-image"><img src="${window.UPSHIFT_ART?.[city.id]||''}" alt="${city.name}城市全景插画"><span>${city.en}</span><i class="panorama-cloud"></i></div><div class="panorama-caption"><div><strong>${l.rest?CLASSES[l.rest.class].name+' · 假期':city.name}</strong><span>${l.rest?'阶级人生 / 恢复与生活':l.district?DISTRICTS[city.id].name:phase(l.energy,l.energyCap)+' / '+CLASSES[cl].name}</span></div><b>${l.rest?'☾':'↗'}</b></div>`;}
  $('life-radio').hidden=true;$('life-rank').hidden=true;
  const map=$('life-map-pull');map.hidden=!!l.rest||!!l.travel||!active;map.setAttribute('aria-label','点击打开世界地图');map.innerHTML=`${glyph('globe')}<span>世界地图</span><b>↗</b>`;
  this.paintTicker();this.paintNews();this.paintContext();
  if(l.travel){const b=$('life-backdrop');b.style.backgroundImage='none';if(!b.querySelector('.flight-scene'))b.innerHTML=`<div class="flight-scene">${plane}<div class="flight-window-label">${l.travel.mode==='ground'?'OVERLAND CONNECTION / 陆海联运':'ABOVE THE CLOUDS / 云端航程'}</div></div>`;b.classList.toggle('overland',l.travel.mode==='ground');}else $('life-backdrop').innerHTML='';
 }
 paintTicker(){const el=$('class-ticker');if(!el)return;const cl=this.s.life.rest?.class??classIndex(this.s);el.hidden=this.c.started?.()===false||!!this.s.life.travel;const key=cl+':'+this.s.life.city;if(el.dataset.key!==key){el.dataset.key=key;const text=CLASS_FEEDS[cl].map(t=>`<span>${t}</span>`).join('');el.innerHTML=`<b>${CLASSES[cl].name} / 生活电台</b><div class="ticker-window"><div class="ticker-track">${text}${text}</div></div>`;}}
 paintNews(){const el=$('world-news');if(!el)return;const l=this.s.life;el.hidden=!l.rest||this.c.started?.()===false;if(el.hidden)return;const n=NEWS.find(n=>n.id===l.news?.id)||NEWS[0];const c=CITY_DATA.find(c=>c.id===n.city);el.innerHTML=`<span class="news-kicker">WORLD DESK / 模拟世界新闻</span><h3>${n.title}</h3><p>${n.body}</p><div><b>${c.name}</b><span>本次假期播报 · 下次休息时更新</span></div>`;}
 paintContext(){const el=$('project-context');if(!el)return;const s=this.s,o=s.offer;el.hidden=this.c.started?.()===false||!!s.life.rest||!!s.life.travel||this.c.visiting?.()||o.type!=='project';if(el.hidden)return;const local=localById(o.localId);el.innerHTML=`<span class="context-kicker">${getCity(s).name} / ${local?.category||'街区项目'}</span><h2>${safe(local?.name||o.localName||'街角的新机会')}</h2><p>${local?.culture||'先看清项目概率与规则，再决定要不要参与。'}</p>${o.newsTitle?`<small>新闻影响：${o.newsTitle}</small>`:''}<span class="context-stem"></span>`;}
 afterDock(){super.afterDock();this.paintContext();}
 interceptDock(){const s=this.s;if(s.life.rest||s.life.travel||s.offer.pendingStake)return super.interceptDock();if(['district-gate','district-task','interlude'].includes(s.offer.type)){this.renderEncounter();return true;}return super.interceptDock();}
 renderEncounter(){const s=this.s,o=s.offer,d=$('game-dock');this.paintContext();d.dataset.kind=o.type;d.style.setProperty('--rarity',DISTRICTS[o.city]?.color||'#6797a0');
  if(o.type==='interlude'){const names={bridge:['走过一座桥。','河面没有报价，只有风。走一小段空白，再回到城市。'],waterfront:['沿着水边走。','暂时没有项目。留一点时间给水光和远处的船。'],park:['穿过街心公园。','树荫下没有盈利预测。你可以歇一口气，再继续走。'],alley:['转进一条小巷。','墙上的旧海报、晾起的衣服，这也是城市的一部分。']};const [title,desc]=names[o.scene];this.interludeUntil=this.interludeId===o.id?this.interludeUntil:Date.now()+3500;this.interludeId=o.id;d.innerHTML=`<span class="life-eyebrow">CITY INTERLUDE / 街边留白</span><h1>${title}</h1><p class="encounter-copy">${desc}</p><div class="interlude-line"><i></i></div><p class="life-note">无投资 · 无现金扣除 · 下一站仍消耗 5 体力</p><button id="interlude-next" class="primary" data-action="next" ${Date.now()<this.interludeUntil?'disabled':''}>${Date.now()<this.interludeUntil?'慢行中…':'继续前行 →'}</button>`;setTimeout(()=>{if(this.s.offer.id===o.id&&$('interlude-next')){$('interlude-next').disabled=false;$('interlude-next').textContent='继续前行 →';}},Math.max(0,this.interludeUntil-Date.now()));}
  else{const e=DISTRICTS[o.district];d.innerHTML=`<div class="event-ribbon">RARE DISTRICT / 地区限定</div><div class="event-emblem">${e.symbol}</div><h1>${e.name}</h1>${o.type==='district-gate'?`<p class="encounter-copy">${e.desc}</p><div class="event-contract"><strong>不是投资，也没有入场费。</strong><p>进入后，剩余站点全部变成特殊任务，直到本轮体力耗尽；期间不能跨城。当前剩余 ${s.life.energy} 体力。</p></div><div class="action-row">${button('decline','这次路过')}${button('enter','走进去 →',o.id,false,'primary')}</div>`:`<h2 class="task-title">${e.tasks[o.task][0]}</h2>${o.settled?`<div class="event-pay"><strong>+${money(o.reward||0)}</strong><p>${safe(o.result||'活动已完成。')}</p></div><button class="primary" data-action="${s.life.energy<=0?'life-prompt-rest':'next'}">${s.life.energy<=0?'体力已耗尽 · 申请休整 🛏️':'下一个特别任务 →'}</button>`:`<p class="life-note">以体力换报酬，不扣除现金。选择后立即结算一次。</p><div class="event-choices">${button('task',`<strong>${e.tasks[o.task][1]}</strong><span>稳妥完成 · −8 体力 · 固定报酬</span>`,'0',s.life.energy<=0)}${button('task',`<strong>${e.tasks[o.task][2]}</strong><span>大胆尝试 · −12 体力 · 65% 额外小费，否则基础报酬</span>`,'1',s.life.energy<=0)}</div><button class="pass-button" data-action="${s.life.energy<=0?'life-prompt-rest':'next'}">${s.life.energy<=0?'体力耗尽 · 申请休整':'跳过任务，继续探索（−5 体力）'}</button>`}<p class="event-until">✦ ${s.life.energy} / ${s.life.energyCap} · 体力耗尽后结束特殊街区</p>`}`;}
  this.c.fit();
 }
 beforeNext(){if(this.s.offer.type==='interlude'&&Date.now()<this.interludeUntil)return false;return super.beforeNext();}
 openAtlas(){const s=this.s,l=s.life;if(l.rest||l.travel||s.offer.pendingStake){this.c.toast('完成当前阶段后再打开世界地图。');return;}const selected=CITY_DATA.find(c=>c.id===this.selected)||getCity(s);const locked=!owns(s,'passport')||l.currentWorth<selected.min*100;const position=c=>[(c.coords[1]+180)/360*100,(90-c.coords[0])/180*100];const offsets={taipei:[-7,4],tokyo:[1,-3],singapore:[-9,4],newyork:[0,3],vegas:[-4,4],monaco:[-3,-7]};
 const markers=CITY_DATA.map(c=>{const [x,y]=position(c),[dx,dy]=offsets[c.id];return `<line x1="${x*10}" y1="${y*5}" x2="${(x+dx)*10}" y2="${(y+dy)*5}" stroke="#e4c57a" stroke-width="1.5"/><circle cx="${x*10}" cy="${y*5}" r="4" fill="${c.id===l.city?'#eff6cd':'#e4c57a'}"/>`;}).join('');
 const pins=CITY_DATA.map(c=>{const [x,y]=position(c),[dx,dy]=offsets[c.id];return `<button class="map-pin ${c.id===selected.id?'selected':''} ${l.currentWorth<c.min*100?'locked':''}" style="left:${x+dx}%;top:${y+dy}%" data-action="life-city" data-value="${c.id}" aria-label="选择${c.name}" aria-pressed="${selected.id===c.id}">${c.name}${c.id===l.city?' ●':''}</button>`;}).join('');
 const choices=CITY_DATA.map(c=>button('city',`${c.name}${l.currentWorth<c.min*100?' · 🔒':''}`,c.id,false,c.id===selected.id?'selected':'')).join('');
 const from=getCity(s);this.c.open('atlas','','',`<div class="atlas-panel world-atlas"><div class="atlas-top"><div><span class="life-eyebrow">THE WORLD / 点击城市选择目的地</span><h2 id="modal-title">下一站，去哪里？</h2></div><button class="atlas-close" data-action="close" aria-label="关闭世界地图">×</button></div><div class="real-map"><svg viewBox="0 0 1000 500" role="img" aria-label="世界大陆地图与六座可探索城市"><rect width="1000" height="500" fill="#172e3f"/><path d="${LAND_PATH}" fill="#385567" stroke="#557484" stroke-width=".7"/><path d="M0 250H1000M0 125H1000M0 375H1000M250 0V500M500 0V500M750 0V500" stroke="#73909b" opacity=".14"/>${markers}</svg>${pins}</div><div class="map-city-list">${choices}</div><div class="map-detail"><div class="map-selected-art"><img src="${window.UPSHIFT_ART?.[selected.id]||''}" alt="${selected.name}全景"><span>${selected.en} / ${LOCAL_PROJECTS[selected.id].length} 个当地项目</span></div><div class="map-copy"><h3>${selected.name} <small>${selected.country}</small></h3><p>${selected.desc}</p><p class="local-special">稀有街区：${DISTRICTS[selected.id].name}</p><small>独立配乐：${CITY_CREDITS.find(c=>c.id===selected.id)?.title}</small></div></div>${!owns(s,'passport')?`<div class="panel-notice">地图随时可看；旅行需要沿途商店的「世界通行证」（$350，当前总身家 $500 解锁）。</div>`:locked?`<div class="panel-notice">前往这里需要当前总身家达到 ${money(selected.min*100)}。</div>`:''}${l.district?'<div class="panel-notice warning">特殊街区进行中，体力耗尽并休息后才能跨城。</div>':''}<div class="map-travel" id="map-travel"></div><p class="life-note">从 ${from.name} 出发 · 自然地理底图：Natural Earth，公共领域 · 交通距离按经纬度估算</p></div>`,{wide:true,custom:true});
 import('./life-core.js').then(({routes})=>{if(!$('map-travel'))return;const blocked=locked||!!l.district||!!s.activeChallenge||selected.id===l.city||l.energy<=0;$('map-travel').innerHTML=routes(s,selected).map(r=>button('travel',`${glyph(r.icon)}<strong>${r.name}</strong><span>${money(r.cost)} · ${r.seconds}秒 · −10 体力</span>`,selected.id+':'+r.id,blocked||s.cash<=r.cost,'map-ticket')).join('');});
 }
 renderRest(){super.renderRest();const cap=this.s.life.energyCap,d=$('game-dock');d.innerHTML=d.innerHTML.replaceAll('200 体力',cap+' 体力');this.paintNews();}
 paintRest(){super.paintRest();if($('rest-status'))$('rest-status').textContent=$('rest-status').textContent.replace('200 体力',this.s.life.energyCap+' 体力');}
 musicId(){if(owns(this.s,'music')&&this.s.life.soundscape==='class'&&this.s.life.rest)return 'class'+this.s.life.rest.class;return getCity(this.s).music;}
 tick(){super.tick();}
 menuExtras(){const l=this.s.life,cost=[150000,400000,1000000,2500000][(l.energyCap-200)/50];return super.menuExtras().replaceAll('/ 200','/ '+l.energyCap)+`<section class="life-menu"><div class="life-eyebrow">PERSONAL SETTINGS / 个人成长</div><div class="life-menu-actions">${button('ui-settings','界面缩放 / 文字大小')}${button('map','点击探索世界')}${button('upgrade',l.energyCap>=400?'体力上限已满 · 400':`提升体力上限 ${l.energyCap} → ${l.energyCap+50} · ${money(cost)}`,'',l.energyCap>=400||!!l.rest||!!l.travel)}</div></section>`;}
 guide(){this.c.open('life-guide','同样的 $100，不同的城市。','Broke to Billionaire: The $100 Start / 3.1 城市增强版',`<div class="life-guide"><h3>体力与昼夜</h3><p>起始 200；菜单可分四次升级至 400，上限每次 +50，费用分别为 $1,500 / $4,000 / $10,000 / $25,000，升级同时补充 50 点体力。前进 −5，投资 −3，购物 −2，旅行 −10。剩余体力决定清晨、午后、黄昏和夜晚。耗尽后进入休息，结束时回满当前上限并回到清晨。</p><h3>不同城市，不同生活</h3><p>六座城市各有 12 个当地项目、独立全景和配乐。每移动 10 格转过街角；小概率经过桥梁、公园、水岸或小巷，这些空白路段不提供投资。地图直接点击，旅行仍保留 3.1 的通行证和财富门槛。</p><h3>地区稀有事件</h3><p>第 4 站起、体力大于 25 且没有限时挑战时，每次生成站点有 4.5% 的机会获得入场邀请。免费选择进入或离开；进入后直到体力耗尽只生成该街区的任务，期间不能跨城。任务不投资、不扣现金：稳妥工作消耗 8 体力、拿固定报酬；大胆尝试消耗 12 体力，65% 得到 2.3 倍报酬，否则获得 0.35 倍基础劳务报酬。跳过仍消耗 5 体力。</p><h3>休息与新闻</h3><p>假期账单、付费活动、立即恢复套餐沿用 3.1；无力支付可申请公共救助。右上角是虚构游戏新闻，不是现实新闻。每次休息更新一条事件，对指定城市下一轮普通项目的成功率或倍率生效，直到下次休息；效果计入投资前显示值。</p><h3>界面与声音</h3><p>右上角 UI − / ＋ 调整面板，Aa 调整字体。文字深浅对比固定，不跟随夜色变暗。所有城市音乐离线内置，首次点击后开始；可在音乐设置中静音或调节音量。</p><p>所有资金和事件均为虚构游戏内容。无充值、无提现、无理财建议。城市图片为 AI 生成示意，不是实景导航地图。</p></div>`);}
 async handle(a,v){
  if(a==='life-scale'){this.settings.scale=Math.max(.75,Math.min(1.25,Math.round((this.settings.scale+Number(v))*100)/100));this.applyUI();if($('modal-card').querySelector('.read-settings'))this.uiSettings();return true;}
  if(a==='life-font'){this.settings.text=Math.max(14,Math.min(22,this.settings.text+Number(v)));this.applyUI();this.uiSettings();return true;}
  if(a==='life-reset-ui'){this.settings={scale:1,text:16};this.applyUI();this.uiSettings();return true;}
  if(a==='life-ui-settings'){this.uiSettings();return true;}
  const s=this.s;
  if(['life-enter','life-decline','life-task','life-upgrade'].includes(a)){
   if(s.ended)return true;
   try{
    if(a==='life-upgrade'){if(s.life.energyCap>=400)return true;const cap=s.life.energyCap,cost=[150000,400000,1000000,2500000][(cap-200)/50];this.c.confirm('扩大你的体力上限？',`支付 ${money(cost)} 游戏币，体力上限 ${cap} → ${cap+50}，同时补充 50 点体力。此升级在破产重开时清除。`,()=>{try{if(this.s!==s)throw Error('本局已经改变。');upgradeEnergy(s);this.persist();this.c.renderDock();this.c.toast('体力上限已提升到 '+s.life.energyCap);}catch(e){this.c.toast(e.message);}});return true;}
    if(a==='life-decline'){if(s.offer.type==='district-gate')await this.c.next();return true;}
    if(a==='life-enter'){if(s.offer.type!=='district-gate'||s.offer.id!==v||s.life.energy<=0||s.life.rest||s.life.travel)return true;s.life.district={city:s.life.city,entered:s.page};s.offer=districtOffer(s);s.lastResult=null;this.c.world.setOffer(s.offer);this.persist();this.c.renderDock();this.c.toast('你进入了 '+DISTRICTS[s.life.city].name+'。直到体力耗尽，都是特别的街区任务。');return true;}
    if(a==='life-task'){const result=districtReward(s,Number(v));markPeak(s);this.c.world.celebrate();this.persist();this.c.renderDock();this.c.toast(`任务报酬 +${money(result.reward)} · 不需要投入本金`);return true;}
   }catch(e){this.c.toast(e.message);}return true;
  }
  return super.handle(a,v);
 }
}
