import {worth,lateTier,TIERS_LATE} from './endgame-core.js';
import {icon} from './ui.js';
const EXTRAS=[{tier:1,action:'history',symbol:'▤',name:'随身账本',desc:'随时回看投资盈亏'},{tier:2,action:'rules',symbol:'◈',name:'风险罗盘',desc:'查看当前项目完整条款'},{tier:3,action:'life-security',symbol:'♜',name:'私人安保',desc:'按需雇佣与调整姿态'},{tier:4,action:'life-show-medals',symbol:'✦',name:'荣誉典藏',desc:'查看孤品与荣誉勋章'},{tier:5,action:'life-status',symbol:'♛',name:'资本印玺',desc:'查看总身家与生活账单'}];
export class ProsperityUI{
 constructor(c){this.c=c;this.last=null;this.pendingUnlock=false;this.nextTick=0;const game=document.getElementById('game');game.insertAdjacentHTML('beforeend','<div id="wealth-badges" aria-label="当前阶级解锁的小机制"></div><div id="rank-performance" aria-live="polite" hidden></div><div id="wealth-corners" aria-hidden="true"><i></i><i></i><i></i><i></i></div>');this.tray=document.getElementById('wealth-badges');this.stage=document.getElementById('rank-performance');this.runId='';}
 refresh(){const s=this.c.run(),w=worth(s),tier=lateTier(s);if(s.id!==this.runId){this.runId=s.id;this.last=null;this.pendingUnlock=false;this.tray.replaceChildren();}const previous=this.last;this.last={w,tier};const game=document.getElementById('game');game.dataset.visualRank=Math.min(5,tier);document.getElementById('wealth-corners').hidden=tier<1;
 if(previous&&w>previous.w)this.pendingUnlock=true;
 const allowed=EXTRAS.filter(e=>e.tier<=tier);const old=[...this.tray.children];for(const el of old){if(!allowed.some(e=>String(e.tier)===el.dataset.tier)&&!el.classList.contains('reclaimed')){el.classList.add('reclaimed');el.disabled=true;el.setAttribute('aria-label',el.textContent+' · 暂时回收');setTimeout(()=>el.remove(),this.c.motion()?900:0);}}
 for(const e of allowed){let el=this.tray.querySelector(`[data-tier="${e.tier}"]:not(.reclaimed)`);if(!el){el=document.createElement('button');el.className='wealth-badge';el.dataset.tier=e.tier;el.dataset.action=e.action;el.innerHTML=`<span>${e.symbol}</span><b>${e.name}<small>${e.desc}</small></b>`;el.title=e.desc;this.tray.append(el);}}
 const list=[...this.tray.querySelectorAll(':not(.reclaimed)[data-tier]')];list.forEach((el,i)=>el.classList.toggle('highest',i===list.length-1));
 if(previous&&previous.tier!==tier&&this.c.started()){const up=tier>previous.tier;this.perform(up,tier,previous.tier);}
 }
 perform(up,tier,oldTier){clearTimeout(this.hideTimer);this.stage.hidden=false;this.stage.className=up?'rank-rise':'rank-fall';this.stage.innerHTML=`<div class="rank-rays"></div><div class="rank-medallion">${up?icon('crown'):icon('lock')}</div><div><small>${up?'A NEW CHAPTER / 阶级晋升':'KEEP YOUR STORY / 暂时回落'}</small><strong>${up?TIERS_LATE[tier].name+'人生，开启！':TIERS_LATE[oldTier].name+'装饰正在收回'}</strong><p>${up?'新的权限、装饰与街头机会已就位。':'低于门槛的功能暂停，已购物品仍然保留；财富回升后恢复。'}</p></div>`;this.c.feedback(up);const a=this.stage.getAnimations();a.forEach(x=>x.cancel());if(this.c.motion())this.stage.animate([{opacity:0,transform:'translateY(-35px) scale(.86)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:650,easing:'cubic-bezier(.2,.9,.25,1.2)'});this.hideTimer=setTimeout(()=>{if(this.c.motion())this.stage.animate([{opacity:1},{opacity:0,transform:'translateY(-25px)'}],{duration:500,fill:'forwards'});setTimeout(()=>{this.stage.hidden=true;},this.c.motion()?500:0);},4500);}
 tick(now){if(now<this.nextTick)return;this.nextTick=now+180;this.tray.hidden=!this.c.started()||!!this.c.run().life.rest||!!this.c.run().life.travel;if(!this.pendingUnlock||!this.c.started()||this.c.blocked()||this.c.run().ended)return;this.pendingUnlock=false;this.c.unlock();}
}
