import {getCity,classIndex,CLASSES} from './life-core.js';
import {worth} from './endgame-core.js';
import {escape as safe} from './ui.js';
// Single in-world interface. Legacy layout preferences migrate without touching the run.
export const LAYOUTS=[{id:'street',name:'沉浸街头'}];
export function applyLayout(meta){meta.layout='street';const app=document.getElementById('app');app.dataset.layout='street';app.dataset.redesign='true';document.body.dataset.layout='street';document.body.dataset.device=meta.device==='phone'?'phone':'desktop';document.documentElement.style.setProperty('--ui-scale',1);}
export function studioMarkup(meta,run){const city=getCity(run);return `<div class="street-start" style="--start-art:url('${window.UPSHIFT_ART?.[city.id]||''}')"><div class="start-brand">LAST $100 <span>白手起家 / STREET STORIES</span></div><div class="start-copy"><div class="start-edition">从一条街，到一整个世界。</div><h1 id="start-title">身无长物。<br>前路<span>有光。</span></h1><p>口袋里的一百块，是故事的第一行。<br>街头投资、陌生人的目光，和慢慢为你打开的城市。</p><button class="start-primary" data-action="onboard-play">${run.page>1?'继续第 '+run.page+' 站':'开始游戏 · $100'} <span>↗</span></button><button class="start-help" data-action="onboard-tour">第一次来？看看怎么玩 →</button><small>完整离线 · 自动保存 · 纯虚拟游戏币</small></div><div class="start-location">01 / ${safe(city.en)}<b>${safe(city.name)}，下一条街见。</b></div><div class="start-footer">世界不需要一开始就很大。<span>STREET EDITION / 5.0</span></div></div>`;}
export function installRedesign(ctx){const app=document.getElementById('app'),game=document.getElementById('game');
 game.insertAdjacentHTML('beforeend',`<div id="street-identity" class="street-identity"></div><nav id="game-navigation" class="street-nav" aria-label="已解锁的街头功能"><button data-action="life-prompt-rest" title="休息与恢复">☾ <span>休息</span></button><button data-action="life-map">◎ <span>旅行</span></button><button data-action="life-status">▤ <span>身家</span></button><button data-action="menu" aria-label="菜单与存档设置">≡</button></nav><div class="street-sign" id="street-sign"></div>`);
 const compact=()=>{app.dataset.compact=String(app.clientWidth<760);game.dataset.compact=app.dataset.compact;ctx.world.resize();};new ResizeObserver(compact).observe(app);window.addEventListener('resize',compact);
 function refresh(){const s=ctx.run(),w=worth(s),city=getCity(s),cl=classIndex(s);app.dataset.wealth=w>=10000000?'rich':w>=50000?'growing':'poor';game.dataset.city=city.id;game.dataset.streetStage=w>=50000?'open':'humble';game.style.setProperty('--city-accent',city.color);document.getElementById('street-identity').textContent=`${CLASSES[cl].name} · ${city.name} · ${s.life.energy}/${s.life.energyCap} 体力`;
 const nav=document.getElementById('game-navigation');nav.querySelector('[data-action="life-map"]').hidden=w<50000;nav.querySelector('[data-action="life-status"]').hidden=w<50000;nav.querySelector('[data-action="life-prompt-rest"]').hidden=w<25000&&s.life.energy>30&&!s.life.rest;
 document.getElementById('street-sign').innerHTML=`<span>${safe(city.en)} / ${String(s.page).padStart(3,'0')}</span><b>${safe(city.tag)}</b>`;
 }
 applyLayout(ctx.meta());compact();refresh();return {refresh,compact};}
