// City stories are generated once per stop, with the outcome roll saved in the offer.
export const REGIONAL_STORIES={
 taipei:[['灯下借一只手','夜市摊主的推车坏了，晚餐高峰马上开始。','扶起摊车','添一盏灯','people','✺'],['骑楼联合市集','老街店主想合办一次周末市集，向有积累的你递来邀请。','协调开市','赞助遮雨棚','industry','⌂'],['河岸文化委托','社区邀请你成为文化季的出资人。你不再只是路过的客人。','共同策展','资助公共舞台','people','◈']],
 tokyo:[['末班车前的便当','车站旁的小店缺一双手，最后一批便当还未送达。','帮忙配送','补齐保温箱','people','▥'],['工坊的样品之夜','独立工坊带来试制样品，希望你安排一次真正的市场验证。','参与验样','提供测试经费','tech','✿'],['匠人基金评审席','你收到一封压印邀请函：决定哪一项传统工艺值得长期支持。','主持评审','设立工艺名额','industry','❖']],
 vegas:[['街头舞台缺了灯','一个小乐队的灯坏了，演出却已经售出了第一张票。','帮忙布台','借出设备费','people','★'],['霓虹驻场试演','制作人向你递来驻场计划，需要一场有观众的试演。','统筹试演','购置舞台装置','industry','✦'],['大道庆典冠名夜','霓虹大道邀你参与公共庆典。每一束灯光都有对应的责任。','策划庆典','赞助安全舞台','capital','♧']],
 singapore:[['港边的最后一箱','码头附近的社区合作社正抢在雨来之前搬运物资。','帮忙清点','支持防雨物资','people','⚓'],['兰花园循环市集','本地创业团队正在试行循环包装，希望你成为第一位合作方。','协助试点','资助回收站','tech','✾'],['绿色港湾圆桌','你被邀请参与一次绿色航运圆桌，讨论从许诺走向落地。','协调方案','赞助试验航线','industry','❧']],
 newyork:[['街角爵士的第一场','一位音乐人正在搬设备。今晚的小演出，可能是他的起点。','帮忙开场','租一支话筒','people','♫'],['车库团队路演','小团队没有漂亮办公室，却准备了一份完整的产品试用。','体验并反馈','提供试用经费','tech','▤'],['街区复兴合伙席','城市更新计划留了一张椅子给你。居民与商户都想被听见。','主持听证','资助公共空间','state','▰']],
 monaco:[['海港帆船的绳结','少年帆船队正在修整缆绳，日落之前还有一次练习。','整理器材','补充救生用品','people','⛵'],['海岸工艺沙龙','当地工匠为一次海岸沙龙准备作品，希望找到认真看待手艺的人。','布置展览','提供展位资金','industry','◇'],['海洋保护委托书','私人海湾的宴会之外，一份海洋保护委托书摆在你面前。','协调行动','认领保护项目','state','♜']]
};
const bandFor=tier=>tier>=3?2:tier>=1?1:0;
const termsFor=band=>[{fee:500,reward:1400,fallback:300},{fee:9000,reward:24000,fallback:4000},{fee:250000,reward:650000,fallback:120000}][band];
export function createRegionalStory(s,tier,rng=Math.random){const band=bandFor(tier);return {id:'region-'+s.life.city+'-'+s.page+'-'+Math.floor(rng()*1e9),type:'regional-story',city:s.life.city,rarity:'rare',settled:false,story:{band,roll:Math.max(0,Math.min(.999999,rng())),tier}};}
export function regionalView(s){const o=s.offer,d=REGIONAL_STORIES[o.city]?.[o.story?.band];if(o.type!=='regional-story'||!d)throw Error('无效的地区事件。');const [title,body,work,support,faction,symbol]=d,terms=termsFor(o.story.band);return {title,body,work,support,faction,symbol,...terms,band:o.story.band,tier:o.story.tier};}
export function resolveRegional(s,choice){const o=s.offer,v=regionalView(s);if(s.ended||s.life.rest||s.life.travel||o.settled)throw Error('这次事件已经结束，或暂时不能处理。');if(!['work','support','leave'].includes(choice))throw Error('请选择一项回应。');let delta=0,relation=0,message='你把机会留给别人，继续走进下一条街。';if(choice==='work'){if(s.life.energy<8)throw Error('需要至少 8 点体力。');s.life.energy-=8;const success=o.story.roll<.7;delta=success?v.reward:v.fallback;relation=success?5:2;message=success?'计划顺利完成。你得到报酬，也留下了一个被记住的名字。':'安排并不完全顺利，但你仍拿到了约定的基础劳务费。';}if(choice==='support'){if(s.cash<=v.fee)throw Error('资金不足，至少保留 $0.01。');delta=-v.fee;relation=10;s.life.cityBoons??={};s.life.cityBoons[o.city]={remaining:3,kind:'insight',source:v.title};message='合作凭证已送达。之后在本城生成的 3 个普通项目获得 +2 个百分点成功率（封顶 95%）。';}s.cash=Math.max(0,Math.min(900000000000000,s.cash+delta));if(relation)s.estate.relations[v.faction]=Math.min(100,(s.estate.relations[v.faction]||0)+relation);o.settled=true;o.story.result={choice,delta,relation,message};s.life.storyLog=Array.isArray(s.life.storyLog)?s.life.storyLog:[];s.life.storyLog.unshift({id:o.id,city:o.city,band:v.band,title:v.title,choice,delta});s.life.storyLog=s.life.storyLog.slice(0,30);return o.story.result;}
export function applyRegionalBoon(s,o){if(o.type!=='project')return;const boon=s.life.cityBoons?.[s.life.city];if(!boon||boon.remaining<=0)return;o.p=Math.min(95,o.p+2);o.localSupport='本城合作凭证：成功率 +2 个百分点';boon.remaining--;}
export function normalizeRegional(s){const raw=s.life.cityBoons||{};s.life.cityBoons=Object.fromEntries(Object.keys(REGIONAL_STORIES).filter(id=>raw[id]?.kind==='insight').map(id=>[id,{kind:'insight',remaining:Math.max(0,Math.min(3,Math.floor(Number(raw[id].remaining)||0))),source:String(raw[id].source||'地区合作').slice(0,60)}]));s.life.storyLog=Array.isArray(s.life.storyLog)?s.life.storyLog.slice(0,30):[];}
