// City stories are generated once per stop, with the outcome roll saved in the offer.
export const REGIONAL_STORIES={
 taipei:[['灯下借一只手','夜市摊主的推车坏了，晚餐高峰马上开始。','扶起摊车','添一盏灯','people','✺'],['骑楼联合市集','老街店主想合办一次周末市集，向有积累的你递来邀请。','协调开市','赞助遮雨棚','industry','⌂'],['河岸文化委托','社区邀请你成为文化季的出资人。你不再只是路过的客人。','共同策展','资助公共舞台','people','◈']],
 tokyo:[['末班车前的便当','车站旁的小店缺一双手，最后一批便当还未送达。','帮忙配送','补齐保温箱','people','▥'],['工坊的样品之夜','独立工坊带来试制样品，希望你安排一次真正的市场验证。','参与验样','提供测试经费','tech','✿'],['匠人基金评审席','你收到一封压印邀请函：决定哪一项传统工艺值得长期支持。','主持评审','设立工艺名额','industry','❖']],
 vegas:[['街头舞台缺了灯','一个小乐队的灯坏了，演出却已经售出了第一张票。','帮忙布台','借出设备费','people','★'],['霓虹驻场试演','制作人向你递来驻场计划，需要一场有观众的试演。','统筹试演','购置舞台装置','industry','✦'],['大道庆典冠名夜','霓虹大道邀你参与公共庆典。每一束灯光都有对应的责任。','策划庆典','赞助安全舞台','capital','♧']],
 singapore:[['港边的最后一箱','码头附近的社区合作社正抢在雨来之前搬运物资。','帮忙清点','支持防雨物资','people','⚓'],['兰花园循环市集','本地创业团队正在试行循环包装，希望你成为第一位合作方。','协助试点','资助回收站','tech','✾'],['绿色港湾圆桌','你被邀请参与一次绿色航运圆桌，讨论从许诺走向落地。','协调方案','赞助试验航线','industry','❧']],
 newyork:[['街角爵士的第一场','一位音乐人正在搬设备。今晚的小演出，可能是他的起点。','帮忙开场','租一支话筒','people','♫'],['车库团队路演','小团队没有漂亮办公室，却准备了一份完整的产品试用。','体验并反馈','提供试用经费','tech','▤'],['街区复兴合伙席','城市更新计划留了一张椅子给你。居民与商户都想被听见。','主持听证','资助公共空间','state','▰']],
 monaco:[['海港帆船的绳结','少年帆船队正在修整缆绳，日落之前还有一次练习。','整理器材','补充救生用品','people','⛵'],['海岸工艺沙龙','当地工匠为一次海岸沙龙准备作品，希望找到认真看待手艺的人。','布置展览','提供展位资金','industry','◇'],['海洋保护委托书','私人海湾的宴会之外，一份海洋保护委托书摆在你面前。','协调行动','认领保护项目','state','♜']]
};
const bandFor=tier=>tier>=3?2:tier>=1?1:0;
const termsFor=band=>[{fee:500,reward:1400,fallback:300},{fee:9000,reward:24000,fallback:4000},{fee:250000,reward:650000,fallback:120000}][band];
/* R9: more stories per band + never repeat a story within a run (returns null when the pool is exhausted). */
export const EXTRA_STORIES=[
 [['雨夜送伞','暴雨突然落下，公交站挤满没带伞的人。便利店老板想找人帮忙分发旧伞。','帮忙分伞','买一箱雨衣','people','☂'],['旧货摊搬家','老奶奶的旧货摊要搬到隔壁街，一车杂物需要人手。','帮忙搬运','付一趟货车钱','people','⌂'],['社区黑板报','街道办要重画社区公告栏，找会写字画画的年轻人。','动手画画','赞助颜料','state','✎']],
 [['小店开业','一家新面包店明天开业，老板缺一个能扛货又会招呼客人的帮手。','帮忙开业','赞助开业花篮','industry','✿'],['少年球队','街区少年足球队缺球衣和教练，孩子们在空地上等了很久。','周末当教练','赞助整套球衣','people','◎'],['夜校讲座','社区夜校邀请你讲一堂“如何攒下第一桶金”。','上台讲课','资助夜校教材','tech','◈']],
 [['老剧院改造','一座百年剧院面临拆除，保护协会希望有人出面。','参与改造方案','出资修缮屋顶','state','♜'],['科技孵化周','年轻创业团队在车库里做路演，想找一位真正的投资人听听。','担任评委','设立创业奖金','tech','⚙'],['港口慈善夜','慈善晚宴筹款重建渔港码头，主持人点名请你发言。','上台致辞','认捐一段码头','capital','⚓']]];
const storyPool=(city,band)=>[REGIONAL_STORIES[city]?.[band],...EXTRA_STORIES[band]].filter(Boolean);
export function createRegionalStory(s,tier,rng=Math.random){const band=bandFor(tier),city=s.life.city;s.life.storySeen=Array.isArray(s.life.storySeen)?s.life.storySeen:[];
 const pool=storyPool(city,band).map((d,v)=>v).filter(v=>!s.life.storySeen.includes(city+':'+band+':'+v));if(!pool.length)return null;
 const v=pool[Math.floor(rng()*pool.length)];s.life.storySeen.push(city+':'+band+':'+v);if(s.life.storySeen.length>200)s.life.storySeen.splice(0,50);
 return {id:'region-'+city+'-'+s.page+'-'+Math.floor(rng()*1e9),type:'regional-story',city,rarity:'rare',settled:false,story:{band,v,roll:Math.max(0,Math.min(.999999,rng())),tier}};}
export function regionalView(s){const o=s.offer,d=storyPool(o.city,o.story?.band)[o.story?.v||0];if(o.type!=='regional-story'||!d)throw Error('无效的地区事件。');const [title,body,work,support,faction,symbol]=d,terms=termsFor(o.story.band);return {title,body,work,support,faction,symbol,...terms,band:o.story.band,tier:o.story.tier};}
export function resolveRegional(s,choice){const o=s.offer,v=regionalView(s);if(s.ended||s.life.rest||s.life.travel||o.settled)throw Error('这次事件已经结束，或暂时不能处理。');if(!['work','support','leave'].includes(choice))throw Error('请选择一项回应。');let delta=0,relation=0,message='你把机会留给别人，继续走进下一条街。';if(choice==='work'){if(s.life.energy<8)throw Error('需要至少 8 点体力。');s.life.energy-=8;const success=o.story.roll<.7;delta=success?v.reward:v.fallback;relation=success?5:2;message=success?'计划顺利完成。你得到报酬，也留下了一个被记住的名字。':'安排并不完全顺利，但你仍拿到了约定的基础劳务费。';}if(choice==='support'){if(s.cash<=v.fee)throw Error('资金不足，至少保留 $0.01。');delta=-v.fee;relation=10;s.life.cityBoons??={};s.life.cityBoons[o.city]={remaining:3,kind:'insight',source:v.title};message='合作凭证已送达。之后在本城生成的 3 个普通项目获得 +2 个百分点成功率（封顶 95%）。';}s.cash=Math.max(0,Math.min(900000000000000,s.cash+delta));if(relation)s.estate.relations[v.faction]=Math.min(100,(s.estate.relations[v.faction]||0)+relation);o.settled=true;o.story.result={choice,delta,relation,message};s.life.storyLog=Array.isArray(s.life.storyLog)?s.life.storyLog:[];s.life.storyLog.unshift({id:o.id,city:o.city,band:v.band,title:v.title,choice,delta});s.life.storyLog=s.life.storyLog.slice(0,30);return o.story.result;}
export function applyRegionalBoon(s,o){if(o.type!=='project')return;const boon=s.life.cityBoons?.[s.life.city];if(!boon||boon.remaining<=0)return;o.p=Math.min(95,o.p+2);o.localSupport='本城合作凭证：成功率 +2 个百分点';boon.remaining--;}
export function normalizeRegional(s){const raw=s.life.cityBoons||{};s.life.cityBoons=Object.fromEntries(Object.keys(REGIONAL_STORIES).filter(id=>raw[id]?.kind==='insight').map(id=>[id,{kind:'insight',remaining:Math.max(0,Math.min(3,Math.floor(Number(raw[id].remaining)||0))),source:String(raw[id].source||'地区合作').slice(0,60)}]));s.life.storyLog=Array.isArray(s.life.storyLog)?s.life.storyLog.slice(0,30):[];}
