import {regionalView,resolveRegional} from './regional-stories.js';
import {TALENTS,crew,hire,dismiss,crewWages,CITY_STREET,passer,opinion,greet,quip} from './street-core.js';
import {worth,billQuote} from './endgame-core.js';
import {getCity} from './life-core.js';
import {escape as safe} from './ui.js';
const money=n=>'$'+(n/100).toLocaleString('en-US',{maximumFractionDigits:2});
const short=n=>n>=1e8?'$'+(n/1e8).toFixed(1)+'M':n>=1e5?'$'+(n/1e5).toFixed(1)+'k':money(n);
const button=(action,text,id='',disabled=false)=>`<button class="life-button" data-action="street-${action}" data-value="${safe(id)}" ${disabled?'disabled':''}>${text}</button>`;
export class StreetUI{
 constructor(ctx){this.c=ctx;this.layer=document.createElement('div');this.layer.id='street-people';document.getElementById('game').append(this.layer);this.c.world.onStreetPositions=points=>this.position(points);this.key='';this.born=performance.now();this.nextTick=0;this.nextQuip=0;this.quipLayer=document.getElementById('street-quips');const panorama=document.getElementById('city-panorama');panorama.tabIndex=0;panorama.setAttribute('role','button');panorama.setAttribute('aria-label','展开当前城市全景');panorama.addEventListener('click',()=>this.panorama());panorama.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.panorama();}});}
 get s(){return this.c.run();}
 interceptDock(){if(this.s.offer.type==='regional-story'&&!this.s.life.rest&&!this.s.life.travel){const d=document.getElementById('game-dock'),v=regionalView(this.s);d.dataset.kind='regional-story';d.innerHTML=`<div class="encounter-ticket">${v.symbol} 城市故事 · ${['街头互助','社群合伙','城市委托'][v.band]}</div><h1>${safe(v.title)}</h1><p>${safe(v.body)}</p><div class="story-preview"><span>${v.symbol}</span><b>${getCity(this.s).name}<small>你的财富地位，改变这次相遇</small></b></div><div class="action-row"><button class="pass-button" data-action="next">继续前行</button><button class="primary" data-action="street-story-open">${this.s.offer.settled?'查看回响':'走进故事'}</button></div>`;this.c.fit();return true;}if(this.s.offer.type!=='talent-market'||this.s.life.rest||this.s.life.travel)return false;const d=document.getElementById('game-dock'),city=CITY_STREET[this.s.life.city];d.dataset.kind='talent-market';d.innerHTML=`<div class="encounter-ticket">✦ 沿途偶遇 / 职业介绍所</div><h1>${city.market}</h1><p>你走到了一处人才招募地点。机会只在这一站，继续前行后市场便会离开视野。</p><div class="market-illustration">⌂ <span>人才正在等一份合适的合约</span></div><div class="action-row"><button class="pass-button" data-action="next">继续走 →</button><button class="primary" data-action="street-market">走进市场</button></div>`;this.c.fit();return true;}

 refresh(){const s=this.s;if(!s.life)return;const w=worth(s),n=[s.id,s.page,s.life.city,crew(s).map(t=>t.id).join(','),s.offer.type==='talent-market'].join(':');this.people=Array.from({length:6},(_,i)=>passer(s,i));
 if(this.key!==n){this.key=n;this.born=performance.now();const city=CITY_STREET[s.life.city];this.layer.innerHTML=`<button class="world-person manager-label" data-action="street-manager" data-anchor="manager"><span class="person-eyebrow">${safe(city.manager)}</span><strong>${safe(city.opening)}</strong><small>点我聊聊项目 ↗</small></button>${s.offer.type==='talent-market'?`<button class="world-person market-label" data-action="street-market" data-anchor="market"><small>TALENT MARKET</small><b>⌂ ${safe(city.market)}</b><span>点此签约 →</span></button>`:''}${crew(s).map(t=>`<button class="world-person crew-label" data-action="street-companion" data-value="${t.id}" data-anchor="crew-${t.id}"><span>◆ ${safe(t.name)} · ${safe(t.role)}</span><small>随行中 · 点击管理</small></button>`).join('')}${this.people.map((p,i)=>`<button class="world-person passer-label" data-action="street-person" data-value="${i}" data-anchor="npc-${i}"><strong>${safe(p.name)} <em>${short(p.cash)}</em></strong><small>${p.rank} · ${p.factionName}</small><small>${safe(p.origin)}来客</small></button>`).join('')}`;this.c.world.setStreetCast(this.people,crew(s),s.offer.type==='talent-market');this.nodes=[...this.layer.querySelectorAll('[data-anchor]')];this.hover=null;this.thoughtAt=0;this.nodes.forEach(el=>{el.addEventListener('pointerenter',()=>{this.hover=el;});el.addEventListener('pointerleave',()=>{if(this.hover===el)this.hover=null;});});}
 const city=CITY_STREET[s.life.city];document.getElementById('game').style.setProperty('--district-ink',city.accent);const dock=document.getElementById('game-dock');dock.style.setProperty('--district-ink',city.accent);
 }
 tick(now){if(now<this.nextTick)return;this.nextTick=now+200;const s=this.s;const hide=!this.c.started()||!!this.c.modal()||this.c.busy()||s.ended||!!s.life.rest||!!s.life.travel;this.layer.hidden=hide;if(hide)return;if(now>=(this.thoughtAt||0)){const visible=this.nodes?.filter(el=>el.classList.contains('passer-label')&&el.style.visibility==='visible').map(el=>Number(el.dataset.value))||[];this.activeIndex=visible.length?visible[Math.floor((now-this.born)/9000)%visible.length]:0;this.thoughtAt=now+9000;}
 // Passers-by no longer carry bubble boxes; they drop a short line that floats away.
 this.floatQuip(now);
 const manager=this.layer.querySelector('.manager-label');if(manager){const result=s.offer.settled?s.lastResult:null;manager.querySelector('strong').textContent=result?result.won?'做成了！这次合作，记住你了。':'这次没成。别让一次结果决定全部。':CITY_STREET[s.life.city].opening;manager.classList.remove('compact');}
 }
 floatQuip(now){
  if(now<this.nextQuip){return;}
  this.nextQuip=now+3400+Math.random()*2600;
  if(!this.quipLayer||!this.nodes)return;
  const visible=this.nodes.filter(el=>el.classList.contains('passer-label')&&el.style.visibility==='visible');
  if(!visible.length)return;
  const el=visible[Math.floor(Math.random()*visible.length)],person=this.people[Number(el.dataset.value)];
  if(!person)return;
  // Only one line at a time keeps the street readable.
  if(this.quipLayer.childElementCount>1)this.quipLayer.firstElementChild.remove();
  const q=quip(this.s,person,worth(this.s));
  const app=document.getElementById('app').getBoundingClientRect();
  const r=el.getBoundingClientRect();
  const node=document.createElement('div');
  node.className='street-quip '+q.tone;
  node.textContent=q.text;
  node.style.left=Math.max(10,Math.min(app.width-240,r.left-app.left+r.width/2-100))+'px';
  node.style.top=Math.max(70,r.top-app.top-44)+'px';
  this.quipLayer.append(node);
  setTimeout(()=>node.remove(),5400);
 }
 position(points){if(this.layer.hidden||!this.nodes)return;const app=document.getElementById('app'),rect=app.getBoundingClientRect(),small=app.clientWidth<760,dock=document.getElementById('game-dock').getBoundingClientRect(),occupied=[];let npc=0;const w=worth(this.s);const limit=small?1:2;const topEdge=small?220:270;
 const sorted=[...this.nodes].sort((a,b)=>{const score=e=>e.classList.contains('passer-label')?10+(Number(e.dataset.value)===this.activeIndex?-1:0):e.classList.contains('crew-label')?1:0;return score(a)-score(b);});
 for(const el of sorted){const pt=points.find(p=>p.id===el.dataset.anchor);if(!pt){el.style.visibility='hidden';continue;}const passer=el.classList.contains('passer-label');if(el===this.hover&&el.style.visibility==='visible'){const x=parseFloat(el.style.left),y=parseFloat(el.style.top);occupied.push({x,y,r:x+el.offsetWidth,b:y+el.offsetHeight});if(passer)npc++;continue;}el.style.visibility='hidden';if(el.dataset.anchor==='manager'&&this.s.offer.type!=='project')continue;const ew=el.offsetWidth||130,eh=el.offsetHeight||44;let x=pt.x-rect.left-ew/2,y=pt.y-rect.top-eh;
 if(!passer){x=Math.max(9,Math.min(rect.width-ew-9,x));y=Math.max(topEdge,Math.min((small?dock.top-rect.top-eh-14:rect.height-eh-40),y));}
 if(!pt.visible||x<4||x+ew>rect.width-4||y<topEdge||y+eh>rect.height-10)continue;
 const box={x,y,r:x+ew,b:y+eh};if(box.r>dock.left-rect.left-8&&box.b>dock.top-rect.top-8&&box.x<dock.right-rect.left+8)continue;
 // Preserve breathing room around other labels and the panorama.
 const pano=document.getElementById('city-panorama');if(!pano.hidden){const pr=pano.getBoundingClientRect();if(box.r>pr.left-rect.left-4&&box.x<pr.right-rect.left+4&&box.b>pr.top-rect.top-4&&box.y<pr.bottom-rect.top+4)continue;}
 if(passer&&npc>=limit)continue;
 if(occupied.some(b=>box.x<b.r+8&&box.r>b.x-8&&box.y<b.b+8&&box.b>b.y-8)){if(!el.classList.contains('crew-label'))continue;y-=eh+12;box.y=y;box.b=y+eh;if(y<topEdge)continue;}
 el.style.left=x+'px';el.style.top=y+'px';el.style.visibility='visible';occupied.push(box);if(passer)npc++;
 }
 }
 story(){if(this.s.offer.type!=='regional-story')return;const s=this.s,v=regionalView(s),result=s.offer.story.result;this.c.open('regional-story',v.title,`${getCity(s).name} · ${['街头互助','社群合伙','城市委托'][v.band]}`,`<div class="regional-theater"><div class="story-stage" style="background-image:linear-gradient(#fff9e133,#fff9e1a8),url('${window.UPSHIFT_ART?.['ui-'+s.life.city]||''}')"><span>${v.symbol}</span><b>${getCity(s).en}</b></div><p>${safe(v.body)}</p>${result?`<div class="story-receipt"><span>✓ 这件事，已经留下回响</span><strong>${result.delta>0?'+':result.delta<0?'−':''}${money(Math.abs(result.delta))}</strong><p>${safe(result.message)}</p><b>阵营关系 +${result.relation}</b></div><button class="primary" data-action="close">带着故事，继续走 →</button>`:`<div class="story-choices"><button data-action="street-story-choice" data-value="work" ${s.life.energy<8?'disabled':''}><i>⚡</i><div><strong>${safe(v.work)}</strong><span>−8 体力 · 70% 报酬 ${money(v.reward)}<br>未达成仍有 ${money(v.fallback)} 基础劳务费</span></div></button><button data-action="street-story-choice" data-value="support" ${s.cash<=v.fee?'disabled':''}><i>✦</i><div><strong>${safe(v.support)} · ${money(v.fee)}</strong><span>阵营关系 +10 · 本城后续 3 个普通项目成功率 +2 个百分点</span></div></button><button data-action="street-story-choice" data-value="leave"><i>↗</i><div><strong>这次先路过</strong><span>不扣钱、不扣体力</span></div></button></div><p class="life-note">结果在遇到时锁定；刷新不重抽，每次相遇只结算一次。</p>`}</div>`);}
 panorama(){if(!this.c.started()||this.c.busy()||worth(this.s)<50000)return;const c=getCity(this.s);this.c.open('street-panorama',c.name+' · 城市全景','主街里的城市，不是另一张地图。',`<div class="panorama-full"><img src="${window.UPSHIFT_ART?.[c.id]||''}" alt="${safe(c.name)}全景插画"><p>${safe(c.desc)}</p><small>财富阶段扩展的城市窗口 · AI 生成城市插画</small></div>`);}
 market(){const s=this.s,w=worth(s),city=CITY_STREET[s.life.city];if(w<25000||s.offer.type!=='talent-market'){this.c.toast('需要在沿途偶遇人才市场，才能签约。');return;}
 const talents=TALENTS.filter(t=>t.city==='any'||t.city===s.life.city);this.c.open('street-market',city.market,'先认识一个人，再多一种做事的方法。',`<div class="talent-intro"><b>${getCity(s).name} · ${crew(s).length}/3 随行名额</b><p>签约费一次支付；工资每次休息收取，计入生活维护。随从不是可转卖的资产。签约后，点击街景里的随从管理或解雇。</p></div><div class="talent-grid">${talents.map(t=>`<article class="talent-card"><span class="talent-avatar" style="--coat:#${t.color.toString(16)}">${t.name.slice(0,1)}</span><div><small>${safe(t.origin)} / ${safe(t.role)}</small><h3>${safe(t.name)}</h3><p>“${safe(t.motto)}”</p></div><p class="talent-effect">${safe(t.effect)}</p><div class="talent-prices"><span>签约 <b>${money(t.fee)}</b></span><span>每次休息 <b>${money(t.wage)}</b></span></div><small>总身家门槛 ${money(t.at)}</small>${button('hire',crew(s).some(x=>x.id===t.id)?'已随行':w<t.at?'尚未解锁':s.cash<=t.fee?'签约资金不足':'签约 · '+money(t.fee),t.id,crew(s).some(x=>x.id===t.id)||crew(s).length>=3||w<t.at||s.cash<=t.fee||!!s.life.rest)}</article>`).join('')}</div><p class="life-note">${crewWages(s)?'当前每次休息工资 '+money(crewWages(s))+'。 ':''}其他城市有当地专属人才：东京尽调、霓虹制作、滨海管家、纽约联络、海港康复。</p>`);}
 companion(id){const t=crew(this.s).find(t=>t.id===id);if(!t)return;const s=this.s;
  this.c.open('street-companion',t.name+' · '+t.role,'随行伙伴 / 点击场景中的人物打开管理',`<div class="companion-profile">
   <div class="companion-card"><span class="talent-avatar" style="--coat:#${t.color.toString(16)}">${t.name.slice(0,1)}</span><div><span class="cc-role">${safe(t.origin)} / ${safe(t.role)}</span><h3>${safe(t.name)}</h3><p class="cc-motto">“${safe(t.motto)}”</p></div></div>
   <div class="companion-effect"><b>随行能力</b>${safe(t.effect)}</div>
   <div class="companion-stats"><div><span>每次休息工资</span><b>${money(t.wage)}</b></div><div><span>下次休息总账单</span><b>${money(billQuote(s).total)}</b></div></div>
   <p class="companion-note">解雇不会退还签约费；能力立即停止，后续休息不再收取工资。当前已生成项目的条款不会回写。休息锁账期间无法调整雇佣。</p>
   ${button('fire','解雇这位随从',id,!!s.life.rest||!!s.life.travel)}
  </div>`);}
 manager(){const s=this.s,c=CITY_STREET[s.life.city],o=s.offer;this.c.open('street-manager',c.manager,getCity(s).name+' / '+(o.category||c.local),`<div class="manager-conversation"><span class="conversation-tag">项目经历 · 第 ${s.page} 站</span><h3>${safe(o.localName||'街区会面')}</h3><p>“${safe(c.pitch)}”</p><p>${safe(o.culture||getCity(s).desc)}</p><div class="thought-card"><small>他对你的看法</small><p>${worth(s)<50000?'你还在起步，不必为了面子把现金全押上。':worth(s)<10000000?'你已经有些积累，谈合作时也更有底气。':'你有资源，但每一个承诺依然需要兑现。'}</p></div>${o.crewBonus?.length?`<p>当前随从加成：${safe(o.crewBonus.join('；'))}</p>`:''}<p>交流不会改变已显示的投资条款。${o.settled?'这次项目已结算，可继续前行。':'请以投资卡中的成功率、返还倍率与风险说明为准。'}</p></div>`);}
 person(index){const n=this.people[Number(index)];if(!n)return;const s=this.s;this.c.open('street-person',n.name+' · '+n.origin+'来客',n.rank+' / '+n.factionName,`<div class="person-conversation"><div class="person-money">${money(n.cash)}<small>这位路人的财富 · 虚构游戏数值</small></div><div class="thought-card"><small>○ ○ 心里的话</small><p>${safe(opinion(s,n,worth(s)))}</p></div><p>与你的阵营关系：${s.estate.relations[n.faction]||0}。每站同一人只能打一次招呼；每站最多 5 人。耗费 1 体力。</p>${button('greet','打个招呼 · 建立关系',String(index),s.life.greetings?.includes(`${s.page}:${n.id}`)||s.life.energy<1)}</div>`);}
 handle(a,v){if(!a.startsWith('street-'))return false;try{switch(a){case 'street-story-open':this.story();break;case 'street-story-choice':{const r=resolveRegional(this.s,v);this.s.peak=Math.max(this.s.peak,worth(this.s));this.c.save();this.c.refresh();this.story();this.c.toast(r.delta>0?'城市回响：报酬 +'+money(r.delta):r.choice==='support'?'合作凭证已入手 · 后续 3 个本城项目获得加成':'这条街记住了你的选择。');break;}case 'street-market':this.market();break;case 'street-hire':{const t=hire(this.s,v,worth(this.s));this.c.save();this.c.refresh();this.c.close();this.refresh();this.c.toast(t.name+' 加入队伍！点击街景中的随从查看能力与工资。');break;}case 'street-companion':this.companion(v);break;case 'street-fire':{const s=this.s,t=crew(s).find(t=>t.id===v);if(!t)break;this.c.confirm('与'+t.name+'结束雇佣？','签约费不退还。能力停止，后续账单不再收取其工资。',()=>{try{if(this.s!==s)throw Error('旅程已变更。');dismiss(s,v);this.c.save();this.c.refresh();this.c.close();this.refresh();this.c.toast(t.name+'已离队。');}catch(e){this.c.toast(e.message);}});break;}case 'street-person':this.person(v);break;case 'street-greet':{const n=this.people[Number(v)];if(!n)break;const delta=greet(this.s,n);this.c.save();this.c.refresh();this.c.toast(n.factionName+'关系 +'+delta+' · 体力 −1');this.person(v);break;}case 'street-manager':this.manager();break;}}catch(e){this.c.toast(e.message);}return true;}
}
