import {TALENTS,crew,hire,dismiss,crewWages,CITY_STREET,passer,opinion,greet} from './street-core.js';
import {worth,billQuote} from './endgame-core.js';
import {getCity} from './life-core.js';
import {escape as safe} from './ui.js';
const money=n=>'$'+(n/100).toLocaleString('en-US',{maximumFractionDigits:2});
const short=n=>n>=1e8?'$'+(n/1e8).toFixed(1)+'M':n>=1e5?'$'+(n/1e5).toFixed(1)+'k':money(n);
const button=(action,text,id='',disabled=false)=>`<button class="life-button" data-action="street-${action}" data-value="${safe(id)}" ${disabled?'disabled':''}>${text}</button>`;
export class StreetUI{
 constructor(ctx){this.c=ctx;this.layer=document.createElement('div');this.layer.id='street-people';document.getElementById('game').append(this.layer);this.c.world.onStreetPositions=points=>this.position(points);this.key='';this.born=performance.now();this.nextTick=0;const panorama=document.getElementById('city-panorama');panorama.tabIndex=0;panorama.setAttribute('role','button');panorama.setAttribute('aria-label','展开当前城市全景');panorama.addEventListener('click',()=>this.panorama());panorama.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.panorama();}});}
 get s(){return this.c.run();}
 refresh(){const s=this.s;if(!s.life)return;const w=worth(s),n=[s.id,s.page,s.life.city,crew(s).map(t=>t.id).join(','),w>=25000].join(':');this.people=Array.from({length:6},(_,i)=>passer(s,i));
 if(this.key!==n){this.key=n;this.born=performance.now();const city=CITY_STREET[s.life.city];this.layer.innerHTML=`<button class="world-person manager-label" data-action="street-manager" data-anchor="manager"><span class="person-eyebrow">${safe(city.manager)}</span><strong>${safe(city.opening)}</strong><small>点我聊聊项目 ↗</small></button>${w>=25000?`<button class="world-person market-label" data-action="street-market" data-anchor="market"><small>TALENT MARKET</small><b>⌂ ${safe(city.market)}</b><span>点此签约 →</span></button>`:''}${crew(s).map(t=>`<button class="world-person crew-label" data-action="street-companion" data-value="${t.id}" data-anchor="crew-${t.id}"><span>◆ ${safe(t.name)} · ${safe(t.role)}</span><small>随行中 · 点击管理</small></button>`).join('')}${this.people.map((p,i)=>`<button class="world-person passer-label" data-action="street-person" data-value="${i}" data-anchor="npc-${i}"><strong>${safe(p.name)} <em>${short(p.cash)}</em></strong><small>${p.rank} · ${p.factionName}</small><small>${safe(p.origin)}来客</small><span class="thought" hidden></span></button>`).join('')}`;this.c.world.setStreetCast(this.people,crew(s),w>=25000);this.nodes=[...this.layer.querySelectorAll('[data-anchor]')];this.hover=null;this.thoughtAt=0;this.nodes.forEach(el=>{el.addEventListener('pointerenter',()=>{this.hover=el;});el.addEventListener('pointerleave',()=>{if(this.hover===el)this.hover=null;});});}
 const city=CITY_STREET[s.life.city];document.getElementById('game').style.setProperty('--district-ink',city.accent);const dock=document.getElementById('game-dock');dock.style.setProperty('--district-ink',city.accent);
 }
 tick(now){if(now<this.nextTick)return;this.nextTick=now+200;const s=this.s;const hide=!this.c.started()||!!this.c.modal()||this.c.busy()||s.ended||!!s.life.rest||!!s.life.travel;this.layer.hidden=hide;if(hide)return;if(now>=(this.thoughtAt||0)){const visible=this.nodes?.filter(el=>el.classList.contains('passer-label')&&el.style.visibility==='visible').map(el=>Number(el.dataset.value))||[];this.activeIndex=visible.length?visible[Math.floor((now-this.born)/9000)%visible.length]:0;this.thoughtAt=now+9000;}const index=this.activeIndex??0;
 this.nodes?.forEach(el=>{if(!el.classList.contains('passer-label'))return;const i=Number(el.dataset.value),thought=el.querySelector('.thought');thought.hidden=i!==index||worth(s)<25000;if(!thought.hidden)thought.textContent=opinion(s,this.people[i],worth(s));});
 const manager=this.layer.querySelector('.manager-label');if(manager){const result=s.offer.settled?s.lastResult:null;manager.querySelector('strong').textContent=result?result.won?'做成了！这次合作，记住你了。':'这次没成。别让一次结果决定全部。':CITY_STREET[s.life.city].opening;manager.classList.toggle('compact',now-this.born>9000&&!result);}
 }
 position(points){if(this.layer.hidden||!this.nodes)return;const app=document.getElementById('app'),rect=app.getBoundingClientRect(),small=app.clientWidth<760,dock=document.getElementById('game-dock').getBoundingClientRect(),occupied=[];let npc=0;const w=worth(this.s);const limit=small?(w<25000?1:2):w<25000?2:4;
 const sorted=[...this.nodes].sort((a,b)=>{const score=e=>e.classList.contains('passer-label')?10+(Number(e.dataset.value)===this.activeIndex?-1:0):e.classList.contains('crew-label')?1:0;return score(a)-score(b);});
 for(const el of sorted){const pt=points.find(p=>p.id===el.dataset.anchor);if(!pt){el.style.visibility='hidden';continue;}const passer=el.classList.contains('passer-label');if(el===this.hover&&el.style.visibility==='visible'){const x=parseFloat(el.style.left),y=parseFloat(el.style.top);occupied.push({x,y,r:x+el.offsetWidth,b:y+el.offsetHeight});if(passer)npc++;continue;}el.style.visibility='hidden';if(el.dataset.anchor==='manager'&&this.s.offer.type!=='project')continue;const ew=el.offsetWidth||130,eh=el.offsetHeight||44;let x=pt.x-rect.left-ew/2,y=pt.y-rect.top-eh;
 if(!passer){x=Math.max(9,Math.min(rect.width-ew-9,x));y=Math.max(small?156:182,Math.min((small?dock.top-rect.top-eh-14:rect.height-eh-40),y));}
 if(!pt.visible||x<4||x+ew>rect.width-4||y<155||y+eh>rect.height-10)continue;
 const box={x,y,r:x+ew,b:y+eh};if(box.r>dock.left-rect.left-8&&box.b>dock.top-rect.top-8&&box.x<dock.right-rect.left+8)continue;
 // Preserve breathing room around other labels and the panorama.
 const pano=document.getElementById('city-panorama');if(!pano.hidden){const pr=pano.getBoundingClientRect();if(box.r>pr.left-rect.left-4&&box.x<pr.right-rect.left+4&&box.b>pr.top-rect.top-4&&box.y<pr.bottom-rect.top+4)continue;}
 if(passer&&npc>=limit)continue;
 if(occupied.some(b=>box.x<b.r+8&&box.r>b.x-8&&box.y<b.b+8&&box.b>b.y-8)){if(!el.classList.contains('crew-label'))continue;y-=eh+12;box.y=y;box.b=y+eh;if(y<155)continue;}
 el.style.left=x+'px';el.style.top=y+'px';el.style.visibility='visible';occupied.push(box);if(passer)npc++;
 }
 }
 panorama(){if(!this.c.started()||this.c.busy()||worth(this.s)<50000)return;const c=getCity(this.s);this.c.open('street-panorama',c.name+' · 城市全景','主街里的城市，不是另一张地图。',`<div class="panorama-full"><img src="${window.UPSHIFT_ART?.[c.id]||''}" alt="${safe(c.name)}全景插画"><p>${safe(c.desc)}</p><small>财富阶段扩展的城市窗口 · AI 生成城市插画</small></div>`);}
 market(){const s=this.s,w=worth(s),city=CITY_STREET[s.life.city];if(w<25000){this.c.toast('总身家 $250 时，人才市场才会开门。');return;}
 const talents=TALENTS.filter(t=>t.city==='any'||t.city===s.life.city);this.c.open('street-market',city.market,'先认识一个人，再多一种做事的方法。',`<div class="talent-intro"><b>${getCity(s).name} · ${crew(s).length}/3 随行名额</b><p>签约费一次支付；工资每次休息收取，计入生活维护。随从不是可转卖的资产。签约后，点击街景里的随从管理或解雇。</p></div><div class="talent-grid">${talents.map(t=>`<article class="talent-card"><span class="talent-avatar" style="--coat:#${t.color.toString(16)}">${t.name.slice(0,1)}</span><div><small>${safe(t.origin)} / ${safe(t.role)}</small><h3>${safe(t.name)}</h3><p>“${safe(t.motto)}”</p></div><p class="talent-effect">${safe(t.effect)}</p><div class="talent-prices"><span>签约 <b>${money(t.fee)}</b></span><span>每次休息 <b>${money(t.wage)}</b></span></div><small>总身家门槛 ${money(t.at)}</small>${button('hire',crew(s).some(x=>x.id===t.id)?'已随行':w<t.at?'尚未解锁':s.cash<=t.fee?'签约资金不足':'签约 · '+money(t.fee),t.id,crew(s).some(x=>x.id===t.id)||crew(s).length>=3||w<t.at||s.cash<=t.fee||!!s.life.rest)}</article>`).join('')}</div><p class="life-note">${crewWages(s)?'当前每次休息工资 '+money(crewWages(s))+'。 ':''}其他城市有当地专属人才：东京尽调、霓虹制作、滨海管家、纽约联络、海港康复。</p>`);}
 companion(id){const t=crew(this.s).find(t=>t.id===id);if(!t)return;this.c.open('street-companion',t.name+' · '+t.role,'随行伙伴 / 点击人物才打开管理',`<div class="companion-profile"><span class="talent-avatar" style="--coat:#${t.color.toString(16)}">${t.name.slice(0,1)}</span><h3>“${safe(t.motto)}”</h3><p class="talent-effect">${safe(t.effect)}</p><div class="talent-prices"><span>每次休息工资 <b>${money(t.wage)}</b></span><span>下次休息总账单 <b>${money(billQuote(this.s).total)}</b></span></div><p>解雇不会退还签约费；能力立即停止，后续休息不再收取工资。当前已生成项目的条款不回写。</p>${button('fire','解雇这位随从',id,!!this.s.life.rest||!!this.s.life.travel)}</div>`);}
 manager(){const s=this.s,c=CITY_STREET[s.life.city],o=s.offer;this.c.open('street-manager',c.manager,getCity(s).name+' / '+(o.category||c.local),`<div class="manager-conversation"><span class="conversation-tag">项目经历 · 第 ${s.page} 站</span><h3>${safe(o.localName||'街区会面')}</h3><p>“${safe(c.pitch)}”</p><p>${safe(o.culture||getCity(s).desc)}</p><div class="thought-card"><small>他对你的看法</small><p>${worth(s)<50000?'你还在起步，不必为了面子把现金全押上。':worth(s)<10000000?'你已经有些积累，谈合作时也更有底气。':'你有资源，但每一个承诺依然需要兑现。'}</p></div>${o.crewBonus?.length?`<p>当前随从加成：${safe(o.crewBonus.join('；'))}</p>`:''}<p>交流不会改变已显示的投资条款。${o.settled?'这次项目已结算，可继续前行。':'请以投资卡中的成功率、返还倍率与风险说明为准。'}</p></div>`);}
 person(index){const n=this.people[Number(index)];if(!n)return;const s=this.s;this.c.open('street-person',n.name+' · '+n.origin+'来客',n.rank+' / '+n.factionName,`<div class="person-conversation"><div class="person-money">${money(n.cash)}<small>这位路人的财富 · 虚构游戏数值</small></div><div class="thought-card"><small>○ ○ 心里的话</small><p>${safe(opinion(s,n,worth(s)))}</p></div><p>与你的阵营关系：${s.estate.relations[n.faction]||0}。每站同一人只能打一次招呼；每站最多 5 人。耗费 1 体力。</p>${button('greet','打个招呼 · 建立关系',String(index),s.life.greetings?.includes(`${s.page}:${n.id}`)||s.life.energy<1)}</div>`);}
 handle(a,v){if(!a.startsWith('street-'))return false;try{switch(a){case 'street-market':this.market();break;case 'street-hire':{const t=hire(this.s,v,worth(this.s));this.c.save();this.c.refresh();this.c.close();this.refresh();this.c.toast(t.name+' 加入队伍！点击街景中的随从查看能力与工资。');break;}case 'street-companion':this.companion(v);break;case 'street-fire':{const s=this.s,t=crew(s).find(t=>t.id===v);if(!t)break;this.c.confirm('与'+t.name+'结束雇佣？','签约费不退还。能力停止，后续账单不再收取其工资。',()=>{try{if(this.s!==s)throw Error('旅程已变更。');dismiss(s,v);this.c.save();this.c.refresh();this.c.close();this.refresh();this.c.toast(t.name+'已离队。');}catch(e){this.c.toast(e.message);}});break;}case 'street-person':this.person(v);break;case 'street-greet':{const n=this.people[Number(v)];if(!n)break;const delta=greet(this.s,n);this.c.save();this.c.refresh();this.c.toast(n.factionName+'关系 +'+delta+' · 体力 −1');this.person(v);break;}case 'street-manager':this.manager();break;}}catch(e){this.c.toast(e.message);}return true;}
}
