import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {newRun,markPeak} from '../src/engine.js';
import {beginRest,payRest} from '../src/life-core.js';
import {resolveEvent,acknowledgeEvent,pendingEvent} from '../src/endgame-core.js';
const results=[];
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage','--host-resolver-rules=MAP last100.test 127.0.0.1']});
const url='http://last100.test:8765/';
const readSave=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('upshift-save-v3')));
const click=(p,a)=>p.locator(`[data-action="${a}"]:visible`).first().click({timeout:15000});
const close=p=>p.locator('#modal-card [data-action="close"]').first().click();
function make(d=100){const s=newRun();s.cash=d*100;markPeak(s);return s;}
async function load(s,w=390,h=844){const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:w<900,isMobile:w<900,deviceScaleFactor:1});await c.addInitScript(({s})=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem('upshift-save-v3',JSON.stringify({version:3,run:s,meta:{lang:'zh',motion:true,low:false,music:false,sound:false,tutorial31:true,legacy:{points:200,lifetime:200,unlocks:[],skin:'default'}}}));localStorage.setItem('last100-ui',JSON.stringify({scale:1,text:16}));sessionStorage.setItem('seeded','1');}},{s});const p=await c.newPage();p.setDefaultTimeout(20000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const external=[];p.on('request',r=>{if(r.url().startsWith('http')&&!r.url().startsWith(url))external.push(r.url())});await p.goto(url,{waitUntil:'load',timeout:120000});await click(p,'onboard-play');await p.waitForTimeout(400);return {c,p,errors,external};}
async function layout(p,name){await p.waitForTimeout(200);const r=await p.evaluate(()=>{const rect=id=>{const e=document.getElementById(id),b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height,right:b.right,bottom:b.bottom,scroll:e.scrollHeight,client:e.clientHeight}};return {world:rect('world'),dock:rect('game-dock'),cash:rect('cash-value'),cashBox:document.querySelector('.cash-hud').getBoundingClientRect().toJSON(),viewport:[innerWidth,innerHeight],summary:rect('capital-summary'),menu:rect('menu-button')};});assert.ok(r.dock.x>=-1&&r.dock.right<=r.viewport[0]+1,`${name} horizontal dock bounds ${JSON.stringify(r)}`);assert.ok(r.dock.y>=70&&r.dock.bottom<=r.viewport[1]+1,`${name} vertical dock bounds`);const intersects=r.world.x<r.dock.right-1&&r.world.right>r.dock.x+1&&r.world.y<r.dock.bottom-1&&r.world.bottom>r.dock.y+1;assert.equal(intersects,false,`${name} scene overlaps dock`);assert.ok(r.world.h>=90&&r.world.w>=120,`${name} scene too small`);assert.ok(r.cash.right<=r.cashBox.right+1,`${name} cash text outside card`);results.push({name,layout:r});await p.screenshot({path:`qa/checked-${name}.png`});}
async function scenario(name,fn){try{await fn();results.push({scenario:name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({scenario:name,status:'FAIL',error:e.stack});console.error('FAIL',name,e.message)}}
await scenario('phone controls, offline, non-secure LAN origin, corner and responsive layouts',async()=>{const s=make();s.life.steps=9;const {p,c,errors,external}=await load(s);try{assert.equal(await p.evaluate(()=>isSecureContext),false);assert.equal(await p.locator('#capital-summary').isVisible(),false);assert.match(await p.locator('#energy-hint').innerText(),/下休/);await layout(p,'phone-poor');const slider=p.locator('#stake-range');const box=await slider.boundingBox();await p.touchscreen.tap(box.x+box.width*.55,box.y+box.height/2);const bet=Number(await p.locator('#stake-input').inputValue());assert.ok(bet>40&&bet<70,'slider responds to touch without reversing behavior');await click(p,'life-culture');assert.equal(await p.locator('#culture-detail').isVisible(),true);await click(p,'life-culture');await c.setOffline(true);await click(p,'next');await p.waitForFunction(()=>!document.getElementById('game').classList.contains('travelling'),{timeout:30000});assert.equal((await readSave(p)).run.life.lastCorner,1);await c.setOffline(false);await layout(p,'phone-after-corner');for(const [w,h,n] of [[320,568,'small-phone'],[844,390,'landscape'],[1024,768,'tablet'],[1440,900,'desktop']]){await p.setViewportSize({width:w,height:h});await layout(p,n);}await click(p,'menu');await click(p,'life-ui-settings');for(let i=0;i<5;i++)await p.locator('[data-action="life-scale"][data-value="0.05"]:visible').click();await close(p);await layout(p,'desktop-scale125');await p.setViewportSize({width:390,height:844});await layout(p,'phone-scale125');await click(p,'menu');await click(p,'life-ui-settings');for(let i=0;i<10;i++)await p.locator('[data-action="life-scale"][data-value="-0.05"]:visible').click();await close(p);await layout(p,'phone-scale75');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);}finally{await c.close();}});
await scenario('rich phone map, menus, material toggle, luxury and persistence',async()=>{const s=make(3e7);s.life.items=['passport'];const {p,c,errors}=await load(s);try{await layout(p,'rich-phone');await click(p,'life-map');assert.equal(await p.locator('.map-pin').count(),6);await p.locator('.map-pin[data-value="tokyo"]').click();assert.match(await p.locator('#modal-card').innerText(),/东京/);await close(p);await click(p,'menu');await click(p,'life-textures');assert.equal(await p.locator('#game').getAttribute('data-wealth-textures'),'off');await close(p);await click(p,'menu');await click(p,'life-luxury');const before=(await readSave(p)).run.cash;await click(p,'life-luxury-buy');await click(p,'confirm');await p.waitForTimeout(250);const after=await readSave(p);assert.equal(after.run.cash,before-100000000);assert.equal(after.run.estate.luxuryEarned,8);const id=after.run.id;await p.reload({waitUntil:'load',timeout:120000});await click(p,'onboard-play');assert.equal((await readSave(p)).run.id,id);assert.equal((await readSave(p)).run.cash,after.run.cash);assert.equal(await p.locator('#game').getAttribute('data-wealth-textures'),'off');assert.deepEqual(errors,[]);}finally{await c.close();}});
await scenario('rest scene, exact worth, small phone activity scrolling, desktop left dock',async()=>{const s=make(3e7);beginRest(s,()=>.99);while(pendingEvent(s)){const ev=pendingEvent(s);resolveEvent(s,ev.id,ev.kind==='health'?'reveal':'comply');acknowledgeEvent(s,ev.id);}payRest(s);s.life.rest.remaining=180000;const {p,c,errors}=await load(s);try{await layout(p,'phone-rest');await click(p,'life-rest-all');assert.equal(await p.locator('.rest-all-grid article').count(),6);await close(p);await click(p,'life-camera');await p.setViewportSize({width:320,height:568});await layout(p,'small-rest');await click(p,'life-rest-all');await close(p);await p.setViewportSize({width:1440,height:900});await layout(p,'desktop-rest');const b=await p.locator('#game-dock').boundingBox();assert.ok(b.x<30);assert.deepEqual(errors,[]);}finally{await c.close();}});
await scenario('health choice result persists on reload; death, ranking and legacy',async()=>{const s=make(10000);s.estate.health=1;s.estate.luxuryEarned=8;beginRest(s,()=>0);const {p,c,errors}=await load(s);try{await p.locator('.event-dialog.health').waitFor();await p.screenshot({path:'qa/checked-health-choice.png'});await click(p,'life-event-choice');await p.locator('.event-dialog.resolved').waitFor();const saved=await readSave(p);assert.equal(saved.run.ended,true);assert.equal(saved.meta.legacy.points,208);await p.reload({waitUntil:'load',timeout:120000});await click(p,'onboard-play');await p.locator('.event-dialog.resolved').waitFor();assert.equal((await readSave(p)).meta.legacy.points,208);await click(p,'life-event-ack');await p.locator('.life-end').waitFor();await p.screenshot({path:'qa/checked-death-phone.png'});await click(p,'leaderboard');assert.match(await p.locator('#modal-card').innerText(),/健康耗尽/);await close(p);await p.locator('.life-end').waitFor();await click(p,'life-legacy');await p.locator('[data-action="life-perk"][data-value="jade"]').click();await p.locator('[data-action="life-skin"][data-value="jade"]').click();assert.equal((await readSave(p)).meta.legacy.skin,'jade');assert.equal((await readSave(p)).meta.legacy.points,200);assert.deepEqual(errors,[]);}finally{await c.close();}});
await browser.close();await fs.writeFile('qa/browser-results.json',JSON.stringify(results,null,2));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
