import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as E from '../src/engine.js';
import * as L from '../src/life-core.js';
import * as C from '../src/endgame-core.js';
import {ASSETS,OUTFITS,PROJECTS} from '../src/catalog.js';
import {LOCAL_PROJECTS,pickLocal} from '../src/city-content.js';
const clone=x=>JSON.parse(JSON.stringify(x));
function run(dollars=100){const s=E.newRun();s.cash=dollars*100;E.markPeak(s);return s;}
function clearEvents(s){for(let limit=0;C.pendingEvent(s)&&!s.ended&&limit<30;limit++){const ev=C.pendingEvent(s);if(ev.resolved){C.acknowledgeEvent(s,ev.id);continue}const v=C.eventView(s,ev);const choice=v.choices.find(c=>c.id==='comply')||v.choices[0];C.resolveEvent(s,ev.id,choice.id);}return s;}
function event(s,kind,extras={}){const e={id:'qa-'+kind,kind,city:s.life.city,base:C.worth(s),tier:C.lateTier(s),resolved:false,ack:false,stage:0,...extras};s.estate.queue=[e];return e;}
test('new life: $100, 200 stamina, five health slots, zero risk',()=>{const s=run();assert.equal(s.cash,10000);assert.equal(s.life.energy,200);assert.equal(s.estate.health,5);assert.equal(C.healthRisk(s),0);assert.equal(C.lateTier(s),0);});
test('net worth counts cash, assets, outfits, utilities and escrow once',()=>{const s=run();s.assets=[ASSETS[0].id];s.outfits=['plain',OUTFITS[1].id];s.life.items=L.ITEMS.map(i=>i.id);s.offer.pendingStake=700;const expected=s.cash+700+ASSETS[0].price*100+OUTFITS[1].price*100+L.ITEMS.reduce((n,x)=>n+x.price*100,0);assert.equal(C.worth(s),expected);assert.equal(E.netWorth(s),expected);assert.equal(L.goodsValue(s),L.ITEMS.reduce((n,x)=>n+x.price*100,0));});
test('current wealth, not peak, controls tiers, guards, services, regions',()=>{const s=run(2e8);s.life.items=['passport'];C.hireGuards(s,2,'cautious');C.enterRegion(s,'industrial');assert.equal(C.activeGuards(s),2);s.cash=100;C.reconcile(s);assert.equal(C.lateTier(s),0);assert.equal(C.activeGuards(s),0);assert.equal(C.activeItem(s,'passport'),false);assert.equal(s.estate.region,'street');assert.ok(s.peak>1e9);assert.equal(L.classIndex(s),0);});
test('every threshold advances, immediately dropping one cent regresses',()=>{for(let i=1;i<C.TIERS_LATE.length;i++){const s=run(C.TIERS_LATE[i].at);assert.equal(C.lateTier(s),i);s.cash--;assert.equal(C.lateTier(s),i-1);}});
test('rest bill freezes; payment decreases current worth, not peak',()=>{const s=run(30e6),prior=C.worth(s),q=C.billQuote(s);L.beginRest(s,()=>.99);assert.equal(s.life.rest.bill.total,q.total);clearEvents(s);const bill=C.restDue(s.life.rest),oldPeak=s.peak;L.payRest(s);assert.equal(C.worth(s),prior-bill);assert.equal(s.peak,oldPeak);assert.equal(s.life.rest.bill.worth,prior);assert.throws(()=>L.payRest(s));});
test('unaffordable mandatory bill kills, no public aid escape',()=>{const s=run(1);L.beginRest(s,()=>.99);clearEvents(s);const r=L.payRest(s,true);assert.equal(r.dead,true);assert.equal(s.ended,true);assert.match(s.estate.death.cause,/账单/);assert.equal(s.life.rest,null);});
test('pending rest choices block paying; chance advances one point each rest',()=>{const s=run(10000);L.beginRest(s,()=>.99);assert.equal(C.pendingEvent(s).risk,1);assert.throws(()=>L.payRest(s));clearEvents(s);L.payRest(s);s.life.rest.remaining=0;L.finishRest(s);L.beginRest(s,()=>.99);assert.equal(C.pendingEvent(s).risk,2);assert.equal(s.estate.health,5);});
test('health roll and result survive serialization; no duplicate hit',()=>{const s=run(10000);L.beginRest(s,()=>0);const ev=C.pendingEvent(s),id=ev.id;C.resolveEvent(s,id,'reveal');assert.equal(s.estate.health,4);const saved=E.validateRun(clone(s));assert.equal(C.pendingEvent(saved).roll,0);assert.equal(C.pendingEvent(saved).resolved,true);assert.throws(()=>C.resolveEvent(saved,id,'reveal'));assert.equal(saved.estate.health,4);});
test('health exhaustion kills and persists death cause and result',()=>{const s=run(10000);s.estate.health=1;L.beginRest(s,()=>0);C.resolveEvent(s,C.pendingEvent(s).id,'reveal');assert.equal(s.ended,true);assert.equal(s.estate.health,0);const loaded=E.validateRun(clone(s));assert.match(loaded.estate.death.cause,/健康/);assert.equal(C.pendingEvent(loaded).resolved,true);});
test('three compliance choices cost 4.5%, reward 6% only once',()=>{const s=run(1e6),ev=event(s,'scandal'),before=s.cash;C.resolveEvent(s,ev.id,'comply');assert.equal(ev.stage,1);C.resolveEvent(s,ev.id,'comply');assert.equal(ev.stage,2);C.resolveEvent(s,ev.id,'comply');assert.equal(s.cash,Math.round(before*1.015));assert.equal(ev.resolved,true);assert.throws(()=>C.resolveEvent(s,ev.id,'comply'));});
test('scandal refusal deducts 14%, hostile fine death records remaining cash',()=>{const s=run(1e6),ev=event(s,'scandal'),before=s.cash;C.resolveEvent(s,ev.id,'refuse');assert.equal(s.cash,before*.86);const a=run(10);const fine=event(a,'scandal',{base:1e9});C.resolveEvent(a,fine.id,'refuse');assert.equal(a.ended,true);assert.equal(a.estate.death.cash,0);});
test('tax agreement does not double-charge; refusal removes tax and hurts state',()=>{for(const choice of ['comply','refuse']){const s=run(1e6);L.beginRest(s,()=>.99);let ev=C.pendingEvent(s);C.resolveEvent(s,ev.id,'reveal');C.acknowledgeEvent(s,ev.id);ev=C.pendingEvent(s);assert.equal(ev.kind,'tax');const before=s.cash,tax=s.life.rest.tax;C.resolveEvent(s,ev.id,choice);assert.equal(s.cash,before);assert.equal(s.life.rest.tax,choice==='refuse'?0:tax);assert.equal(s.estate.relations.state,choice==='refuse'?-28:8);}});
test('security policy changes probabilities; robbery loses 22%; assassination kills',()=>{const s=run(1e6),before=C.securityOdds(s);C.hireGuards(s,3,'cautious');const after=C.securityOdds(s);assert.ok(after.robbery<before.robbery);assert.ok(after.dodge>before.dodge);let ev=event(s,'security',{threat:'robbery',odds:{dodge:0},roll:99});const cash=s.cash;C.resolveEvent(s,ev.id,'resist');assert.equal(s.cash,cash-Math.floor(cash*.22));ev=event(s,'security',{threat:'assassination',odds:{dodge:0},roll:99});C.resolveEvent(s,ev.id,'evade');assert.equal(s.ended,true);});
test('luxury only consumes wealth and awards life points; one purchase per item',()=>{const s=run(1e8),before=C.worth(s),item=C.luxuries(s)[0];C.consumeLuxury(s,item.id);assert.equal(C.worth(s),before-item.price);assert.equal(s.estate.luxuryEarned,item.points);assert.throws(()=>C.consumeLuxury(s,item.id));assert.equal(s.assets.length,0);});
test('legacy settles once, unlock prices deducted once, perks apply next life',()=>{const s=run(1e8),meta={};s.estate.luxuryEarned=100;C.collectLegacy(s,meta);assert.equal(meta.legacy,undefined);C.endLife(s,'qa');C.collectLegacy(s,meta);C.collectLegacy(s,meta);assert.equal(meta.legacy.points,100);C.buyPerk(meta,'constitution');assert.equal(meta.legacy.points,40);assert.throws(()=>C.buyPerk(meta,'constitution'));const next=run();C.applyLegacy(next,meta);assert.equal(next.estate.health,6);assert.equal(next.cash,10000);});
test('medical treatments charge money and restore health or reduce risk',()=>{const s=run(1e9);s.estate.health=3;s.estate.age=30;const before=s.cash;C.buyMedical(s,'care');assert.equal(s.estate.health,4);assert.ok(s.cash<before);C.buyMedical(s,'longevity');assert.equal(C.healthRisk(s),18);assert.equal(s.estate.medicalUses,2);});
test('old unpaid rest save gains one locked bill and one health event, not per reload',()=>{const s=run(1e6);L.beginRest(s,()=>.99);delete s.estate;delete s.life.rest.bill;delete s.life.rest.extra;const a=E.validateRun(clone(s));assert.ok(a.life.rest.bill);assert.equal(a.estate.age,1);assert.equal(a.estate.queue.filter(e=>e.kind==='health').length,1);const b=E.validateRun(clone(a));assert.equal(b.estate.age,1);assert.deepEqual(b.life.rest.bill,a.life.rest.bill);assert.equal(b.estate.queue.length,a.estate.queue.length);});
test('old paid rest is not charged again and gets no retroactive health draw',()=>{const s=run(1e6);L.beginRest(s,()=>.99);clearEvents(s);L.payRest(s);delete s.estate;delete s.life.rest.bill;const cash=s.cash;const a=E.validateRun(clone(s));assert.equal(a.life.rest.paid,true);assert.equal(a.cash,cash);assert.equal(a.estate.queue.length,0);});
test('acknowledged street event remains valid after future rest filters queue',()=>{const s=run(1e6),ev=event(s,'faction',{faction:'people',hostile:false});s.offer={id:'street-event',type:'world-event',eventId:ev.id,city:'taipei',rarity:'rare',settled:false};C.resolveEvent(s,ev.id,'refuse');C.acknowledgeEvent(s,ev.id);L.beginRest(s,()=>.99);assert.doesNotThrow(()=>E.validateRun(clone(s)));assert.equal(s.offer.type,'interlude');});
test('96 local projects have valid catalog and implemented model IDs; gated draw',()=>{const ids=new Set(),models=fs.readFileSync(new URL('../src/local-models.js',import.meta.url),'utf8');for(const [city,ps] of Object.entries(LOCAL_PROJECTS)){assert.equal(ps.length,16);for(const p of ps){assert.ok(!ids.has(p.id));ids.add(p.id);assert.ok(PROJECTS.some(x=>x.id===p.project),p.project);assert.ok(models.includes("'"+p.model+"'"),p.model);}for(let i=0;i<100;i++){const p=pickLocal(city,()=>i/100,100);assert.ok(!p.at||p.at<=100);}}assert.equal(ids.size,96);});
test('seeded multi-life smoke keeps finite cents, valid saves and regression',()=>{let seed=123456789;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);for(const dollars of [100,1e5,1e7,1e10,1e12]){let s=run(dollars);for(let n=0;n<100&&!s.ended;n++){if(C.pendingEvent(s)){const ev=C.pendingEvent(s),view=C.eventView(s,ev);if(ev.resolved)C.acknowledgeEvent(s,ev.id);else{const choices=view.choices.filter(c=>!c.cost||c.cost<s.cash);C.resolveEvent(s,ev.id,choices[Math.floor(rng()*choices.length)].id);}}else if(s.life.rest){if(!s.life.rest.paid)L.payRest(s);else{s.life.rest.remaining=0;L.finishRest(s);}}else if(s.life.energy<8)L.beginRest(s,rng);else E.next(s,{},rng);assert.ok(Number.isSafeInteger(s.cash)&&s.cash>=0);s=E.validateRun(clone(s));assert.equal(C.worth(s),E.netWorth(s));}}});

test('health deterioration grows by one point until natural 100% ceiling',()=>{const s=run();s.estate.age=99;assert.equal(C.healthRisk(s),99);assert.equal(C.healthRisk(s,true),100);s.estate.age=120;assert.equal(C.healthRisk(s),100);s.estate.riskReduction=25;assert.equal(C.healthRisk(s),95);});
