import test from 'node:test';import assert from 'node:assert/strict';
import * as C from '../src/v9-core.js';import * as X from '../src/v12-core.js';
function mk(cash){return {cash,page:1,life:{city:'taipei',energy:100,energyCap:200,items:[]},estate:{health:2,maxHealth:3,age:10,riskReduction:0},assets:[],v9:{}};}
test('kiosk vitamins cut decline by hundredths and triple in price',()=>{const s=mk(50000);C.st(s);const g=X.findGood(s,'vitamins');const p1=X.goodPrice(s,g);assert.equal(X.famEffect(s,g).riskCut,.05);s.offer={type:'v12-shop',goods:[{id:'vitamins',price:p1,sold:false},{id:'checkup2',price:1,sold:false}]};X.buyGood(s,0);assert.equal(s.estate.riskReduction,.05);assert.equal(X.goodPrice(s,g),p1*3);assert.ok(X.famEffect(s,g).riskCut<.05);});
test('LV goods hidden before Magnate, escalate after',()=>{const s=mk(50000);C.st(s);for(let i=0;i<30;i++){const o=X.shopOffer(s,Math.random);assert.ok(o.goods.every(x=>!X.findGood(s,x.id)?.lv),'lv good leaked early');}const r=mk(200000000);C.st(r);assert.equal(C.lvOpen(r),true);const g=X.findGood(r,'postcard');const p=X.goodPrice(r,g);r.offer={type:'v12-shop',goods:[{id:'postcard',price:p,sold:false},{id:'suitcase',price:1,sold:false}]};X.buyGood(r,0);assert.equal(X.goodPrice(r,g),p*2);});
test('hospital heal is a paid chance; failure still charges',()=>{const s=mk(1000000);C.st(s);const d=C.PLACE_OPTS.hospital.find(x=>x.id==='clinic');const q=C.quoteOpt(s,d);assert.ok(q.cost>=60000);const r=C.resolveOpt(s,d,()=>.99);assert.equal(r.healFail,1);assert.equal(s.estate.health,2);assert.equal(s.cash,1000000-q.cost);assert.ok(C.quoteOpt(s,d).cost>q.cost);});
test('health partners exist and are probabilistic',()=>{const ids=['herbalist','coach','monk','biotech','doctor'];for(const id of ids){const p=C.getPartner(id);assert.ok(p);assert.ok(p.deals.some(d=>d.riskP||d.healP));}});
test('luxury needs LV unlock and doubles',()=>{const s=mk(50000000);C.st(s);assert.equal(C.lvOpen(s),false);const x=C.LUXURY[0];const p=C.luxPrice(s,x);C.st(s).lux.push('handbag');assert.equal(C.luxPrice(s,x),p*2);});
test('R11 stroll and promo nodes settle once with correct costs',()=>{const s=mk(100000);C.st(s);s.offer=X.strollOffer(s,()=>0);const e0=s.life.energy;X.takeStroll(s,'walk');assert.equal(s.life.energy,e0+10);assert.throws(()=>X.takeStroll(s,'walk'));
 s.offer=X.promoOffer(s,()=>0);const fee=X.promoFee(s),c0=s.cash;X.settlePromo(s,'pay');assert.equal(s.cash,c0-fee);assert.throws(()=>X.settlePromo(s,'pay'));
 s.offer=X.promoOffer(s,()=>0);const c1=s.cash;X.settlePromo(s,'watched');assert.ok(s.cash>c1);s.offer=X.promoOffer(s,()=>0);X.settlePromo(s,'nofill');});
