import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import {newRun,markPeak} from '../src/engine.js';
import {decorateOffer} from '../src/life-core.js';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage']});
const errors=[];
async function shot(name,{cash=100,city='taipei',energy=200,width=1280,height=820,after}={}){
 const c=await browser.newContext({viewport:{width,height}});
 const run=newRun();run.cash=cash*100;run.life.city=city;run.life.energy=energy;markPeak(run);
 if(city!=='taipei')run.offer=decorateOffer(run,run.offer,()=>.61);
 await c.addInitScript(seed=>{localStorage.setItem('upshift-save-v3',JSON.stringify(seed));},{version:3,run,meta:{layout:'street',music:false,sound:false,low:true,motion:true}});
 const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(name+': '+e.message));
 await p.goto('http://127.0.0.1:8080/',{waitUntil:'load',timeout:120000});
 await p.locator('[data-action="onboard-play"]').click();
 await p.locator('#start-screen').waitFor({state:'hidden'});
 await p.waitForTimeout(1500);
 if(after)await after(p);
 await p.screenshot({path:'qa/shot-'+name+'.png',timeout:60000,animations:'disabled'});
 await c.close();
}
const click=async(p,a,v)=>{const sel=`button[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}:visible`;const m=p.locator('#modal:not([hidden]) '+sel);await (await m.count()?m:p.locator(sel)).first().click();await p.waitForTimeout(900);};
await shot('poor-desktop',{});
await shot('poor-phone',{width:390,height:844});
await shot('growing-desktop',{cash:2000});
await shot('rich-desktop',{cash:2000000});
await shot('rich-phone',{cash:2000000,width:390,height:844});
await shot('crew-panel',{cash:2000,after:async p=>{await click(p,'street-market');await click(p,'street-hire','guide');await p.waitForTimeout(600);const b=p.locator('[data-action="street-companion"]:visible').first();if(await b.count())await b.click();await p.waitForTimeout(700);}});
await shot('rest-desktop',{cash:2000,energy:0,after:async p=>{await click(p,'life-prompt-rest');}});
await shot('status',{cash:2000000,after:async p=>{await click(p,'life-status');}});
await shot('map',{cash:2000000,after:async p=>{await click(p,'life-map');}});
console.log('ERRORS',errors);
await browser.close();
