import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {newRun,markPeak} from '../src/engine.js';
import {decorateOffer} from '../src/life-core.js';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage']});
const errors=[],results=[];let p,c;
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);if(p)await p.screenshot({path:'qa/street-failure-'+results.length+'.png'}).catch(()=>{});}}
async function seed({cash=100,city='taipei',energy=200,companions=[],width=1280,height=820,file=false}={}){await c?.close();c=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const run=newRun();run.cash=cash*100;run.life.city=city;run.life.energy=energy;run.life.companions=companions;markPeak(run);if(city!=='taipei')run.offer=decorateOffer(run,run.offer,()=>.61);await c.addInitScript(seed=>{if(!sessionStorage.getItem('street-seed')){localStorage.setItem('upshift-save-v3',JSON.stringify(seed));sessionStorage.setItem('street-seed','1');}},{version:3,run,meta:{layout:'journal',music:false,sound:false,low:true,motion:true}});p=await c.newPage();p.setDefaultTimeout(18000);p.on('pageerror',e=>errors.push(e.message));await p.goto(file?'file:///home/user/game/index.html':'http://127.0.0.1:8080/',{waitUntil:'load',timeout:120000});await p.locator('[data-action="onboard-play"]').click();await p.locator('#start-screen').waitFor({state:'hidden'});await p.waitForTimeout(600);}
const click=async(a,v)=>{const sel=`button[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}:visible`;const inModal=p.locator('#modal:not([hidden]) '+sel);await (await inModal.count()?inModal:p.locator(sel)).first().click();};
const save=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('upshift-save-v3')));
async function bounds(){const res=await p.evaluate(()=>{const app=document.getElementById('app').getBoundingClientRect();return ['world','game-dock','milestone-progress-bar','cash-value','street-identity','game-navigation'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,ok:r.width>0&&r.height>0&&r.left>=app.left-1&&r.right<=app.right+1&&r.top>=app.top-1&&r.bottom<=app.bottom+1,rect:[r.x,r.y,r.width,r.height]}})});assert.ok(res.every(r=>r.ok),JSON.stringify(res));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
await check('poor UI: visible progress, no external columns, responsive bounds and offline file',async()=>{
 await seed({file:true});assert.equal(await p.locator('#milestone-progress-bar').isVisible(),true);assert.match(await p.locator('#milestone-progress-bar').innerText(),/40%/);assert.equal(await p.locator('.street-nav [data-action="life-map"]').isVisible(),false);assert.equal(await p.locator('#city-panorama').isVisible(),false);assert.equal(await p.evaluate(()=>window.upshift===undefined),true);
 for(const [width,height] of [[1280,820],[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.waitForFunction(()=>document.getElementById('app').dataset.compact===String(innerWidth<760));await p.waitForTimeout(700);await bounds();const sizes=await p.evaluate(()=>({world:document.getElementById('world').clientHeight,app:document.getElementById('app').clientHeight}));assert.equal(sizes.world,sizes.app);if(width===390)await p.screenshot({path:'qa/street-final-poor-phone.png'});}
 await p.setViewportSize({width:390,height:844});await click('invest');await p.locator('.result-panel').waitFor();assert.equal((await save()).run.investments,1);await p.screenshot({path:'qa/street-final-result-phone.png'});
});
await check('market hire → persistent crew → click follower → fire confirmation',async()=>{
 await seed({cash:700});await p.locator('[data-action="street-market"]').waitFor({state:'visible'});await click('street-market');await p.locator('.talent-grid').waitFor();await click('street-hire','guide');await p.locator('#modal').waitFor({state:'hidden'});assert.equal((await save()).run.cash,62000);assert.deepEqual((await save()).run.life.companions,['guide']);await p.locator('[data-action="street-companion"]').waitFor({state:'visible'});await p.screenshot({path:'qa/street-final-crew-desktop.png'});await click('street-companion','guide');assert.match(await p.locator('#modal-card').innerText(),/每次休息工资/);await click('street-fire','guide');await click('confirm');assert.deepEqual((await save()).run.life.companions,[]);assert.equal((await save()).run.cash,62000);
});
await check('phone market and entourage remain accessible, panorama restored to main world',async()=>{
 await seed({cash:2000,width:390,height:844});await bounds();assert.equal(await p.locator('#city-panorama').isVisible(),true);await p.locator('#city-panorama').click();await p.locator('.panorama-full').waitFor();await click('close');await click('street-market');await click('street-hire','guide');await p.locator('#modal').waitFor({state:'hidden'});await p.locator('[data-action="street-companion"]:visible').waitFor();await click('street-companion','guide');await p.screenshot({path:'qa/street-final-crew-phone.png'});await click('close');await p.screenshot({path:'qa/street-final-growing-phone.png'});
});
await check('NPC greet changes relationship once, contextual manager has readable local dialog',async()=>{
 const npc=p.locator('[data-action="street-person"]:visible').first();await npc.waitFor();await npc.click();await p.locator('.thought-card').waitFor();const before=(await save()).run.life.energy;await click('street-greet');assert.equal((await save()).run.life.energy,before-1);assert.equal(await p.locator('[data-action="street-greet"]').isDisabled(),true);await click('close');await click('street-manager');assert.match(await p.locator('#modal-card').innerText(),/林老板|台北/);await click('close');
});
await check('backup export and restore retain companions and are key-free',async()=>{
 await click('menu');await click('settings');const download=p.waitForEvent('download');await click('backup-export');const dl=await download;const data=JSON.parse(await fs.readFile(await dl.path(),'utf8'));assert.deepEqual(data.run.life.companions,['guide']);assert.ok(!JSON.stringify(data).includes('ghp_'));await p.locator('#backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});assert.deepEqual((await save()).run.life.companions,['guide']);await p.locator('#backup-file').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await click('confirm');assert.deepEqual((await save()).run.life.companions,['guide']);
});
await check('rest confirmation displays wages, can settle health and pay bill',async()=>{
 await seed({cash:2000,energy:0,companions:['guide'],width:390,height:844});await click('life-prompt-rest');await p.locator('.confirm-rest-dialog').waitFor();assert.match(await p.locator('#modal-card').innerText(),/随从工资/);await click('life-confirm-start-rest');await p.locator('.event-dialog.health').waitFor();await click('life-event-choice');await click('life-event-ack');await p.locator('[data-action="life-pay"]:visible').waitFor();await click('life-pay');const r=(await save()).run;assert.equal(r.life.rest.paid,true);assert.equal(r.life.rest.bill.companions,600);await p.screenshot({path:'qa/street-final-rest-phone.png'});
});
await check('different cities: local projects, local hiring and rich screen',async()=>{
 await seed({cash:2000000,city:'tokyo'});await click('street-market');assert.match(await p.locator('#modal-card').innerText(),/凛/);assert.doesNotMatch(await p.locator('.talent-grid').innerText(),/林姐/);await click('close');await p.screenshot({path:'qa/street-final-tokyo.png'});await click('life-map');await p.locator('.map-city-list').waitFor();assert.equal(await p.locator('.map-city-list button').count(),6);await click('life-city','monaco');assert.match(await p.locator('.map-copy').innerText(),/摩纳哥/);await click('close');
});
await check('network-blocked production HTML: load, start and invest with zero page errors',async()=>{
 await c.close();c=await browser.newContext({viewport:{width:1024,height:768}});const requested=[];await c.route(/^https?:/,r=>{requested.push(r.request().url());return r.abort();});p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///home/user/game/index.html',{timeout:120000});await click('onboard-play');await click('invest');await p.locator('.result-panel').waitFor();assert.deepEqual(requested,[]);assert.deepEqual(errors,[]);
});
await fs.writeFile('qa/street-browser-results.json',JSON.stringify({results,errors},null,2));await browser.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
